#ifndef __wrapper_ClassSeven__double_ExampleBackendForGAMBIT_1_234_hpp__
#define __wrapper_ClassSeven__double_ExampleBackendForGAMBIT_1_234_hpp__


#include "wrapper_ClassSeven__double_decl.hpp"
#include "wrapper_ClassSeven__double_def.hpp"


#endif /* __wrapper_ClassSeven__double_ExampleBackendForGAMBIT_1_234_hpp__ */
