#ifndef __wrapper_ClassNine__ClassEight_ExampleBackendForGAMBIT_1_234_hpp__
#define __wrapper_ClassNine__ClassEight_ExampleBackendForGAMBIT_1_234_hpp__


#include "wrapper_ClassNine__ClassEight_decl.hpp"
#include "wrapper_ClassNine__ClassEight_def.hpp"


#endif /* __wrapper_ClassNine__ClassEight_ExampleBackendForGAMBIT_1_234_hpp__ */
