#ifndef __wrapper_ClassThree__double_ExampleBackendForGAMBIT_1_234_hpp__
#define __wrapper_ClassThree__double_ExampleBackendForGAMBIT_1_234_hpp__


#include "wrapper_ClassThree__double_decl.hpp"
#include "wrapper_ClassThree__double_def.hpp"


#endif /* __wrapper_ClassThree__double_ExampleBackendForGAMBIT_1_234_hpp__ */
