# GAMBIT: Global and Modular BSM Inference Tool  
#************************************************
# \file                                         
#                                                
#  Cmake linking and rpath commands for GAMBIT.  
#                                                
#  This file has been automatically generated by 
#  scanner+_harvester.py.  Please do not modify. 
#                                                
#************************************************
#                                                
#  Authors:                                      
#                                                
#  \author The GAMBIT Collaboration             
#  \date 11:50AM on July 17, 2020
#                                                
#************************************************
                                                 
if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")     
else()
endif()
