//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Compile-time generation of extra code in Elements
///  that uses the Printers. Required to avoid the use
///  of printers in the standalones.
///
///  Classes added:
///  - Suspicious point exception class.
///
///  This file was automatically generated by     
///  elements_extras.py. Do not modify.           
///
///  *********************************************
///
///  Authors:
///
///  \author The GAMBIT Collaboration            
///  \date 11:47PM on April 24, 2025
///
///  *********************************************

#ifndef __elements_extras_hpp__
#define __elements_extras_hpp__

#include <map>
#include <set>
#include <string>
#include <exception>
#include <vector>
#include <utility>

#include "gambit/Utils/util_macros.hpp"
#include "gambit/Logs/log_tags.hpp"

namespace Gambit
{

  /// Gambit suspicious point exception class.
  class Suspicious_point_exception
  {

    public:

      /// Constructor
      Suspicious_point_exception() {}

      /// Raise the suspicious point exception. Print it with a message and a code. The default code is 1.
      void raise(const std::string &msg, int code=1, bool debug=false)
      {
        if (debug) std::cout << "Point Suspicious (" << code << "): " << msg << std::endl;
      }

  };

  /// Postprocessor reader retrieve function
  template<typename T>
  bool pp_reader_retrieve(T&, str)
  {
    invalid_point().raise("Reader not available in standalones.");
    return false;
  }
}

#endif
