#ifndef __boss__classes_ExampleBackend_1_234_hpp__
#define __boss__classes_ExampleBackend_1_234_hpp__

#ifndef __classes_hpp__
#define __classes_hpp__

#include <iostream>
#include <vector>
#include <ctime>
#include <map> 



#include "backend_types/ExampleBackend_1_234/abstract_ClassThree.hpp"
#include "gambit/Backends/abstracttypedefs.hpp"
#include "gambit/Backends/wrappertypedefs.hpp"
template <typename T>         
class ClassThree : public virtual Abstract_ClassThree<T> {
public:
  T pop();
  void push(T item);
  int size();

private:
  std::vector<T> stack;
  int curr_size;

  public:
    Abstract_ClassThree<T>* pointer_copy__BOSS();

    using Abstract_ClassThree<T>::pointer_assign__BOSS;
    void pointer_assign__BOSS(Abstract_ClassThree<T>* in);


};

// A dummy instantiation to ensure the <double> specialization is generated by the compiler
static ClassThree<double> __BOSS_dummy_ClassThree_double_instance__;

// Second instantiaion with <int> specializatin
static ClassThree<int> __BOSS_dummy_ClassThree_int_instance__;


#include "backend_types/ExampleBackend_1_234/abstract_ClassFour.hpp"
#include "gambit/Backends/abstracttypedefs.hpp"
#include "gambit/Backends/wrappertypedefs.hpp"
class ClassFour : public virtual Abstract_ClassFour {
public:
  double pop();
  void push(double item);
  int size();

private:
  std::vector<double> stack;
  int curr_size;

  public:
    Abstract_ClassFour* pointer_copy__BOSS();

    using Abstract_ClassFour::pointer_assign__BOSS;
    void pointer_assign__BOSS(Abstract_ClassFour* in);


};

template <typename T>
class ClassFive;

#include "backend_types/ExampleBackend_1_234/abstract_ClassFive.hpp"
#include "gambit/Backends/abstracttypedefs.hpp"
#include "gambit/Backends/wrappertypedefs.hpp"
template<>
class ClassFive<ClassFour> : public virtual Abstract_ClassFive<ClassFour>, public ClassThree<ClassFour>
{
public:
  ClassFour pop();
  void push(ClassFour item);
  int size();

  public:
    Abstract_ClassFive<ClassFour>* pointer_copy__BOSS();

    using Abstract_ClassFive<ClassFour>::pointer_assign__BOSS;
    void pointer_assign__BOSS(Abstract_ClassFive<ClassFour>* in);


  public:
    Abstract_ClassFour* pop__BOSS();

    void push__BOSS(Abstract_ClassFour&);

};


#endif
#endif /* __boss__classes_ExampleBackend_1_234_hpp__ */
