//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Rollcall header for model VLQ in
///  ColliderBit.
///
///  Automatically generated by GUM.
///
///  \author The GAMBIT Collaboration
///          http://gambit.hepforge.org
///  \date 11:38AM on June 05, 2024
///
///  *********************************************

#pragma once

#define MODULE ColliderBit


  // Construct an SLHAea object with spectrum and decays for Pythia
  #define CAPABILITY SpectrumAndDecaysForPythia

    #define FUNCTION getSpectrumAndDecaysForPythia_VLQ
    START_FUNCTION(SLHAstruct)
    DEPENDENCY(decay_rates, DecayTable)
    DEPENDENCY(VLQ_spectrum, Spectrum)
    ALLOW_MODEL(VLQ)
    #undef FUNCTION

  #undef CAPABILITY


  // Get Monte Carlo event generator
  #define CAPABILITY HardScatteringSim

    #define FUNCTION getPythia_VLQ
    START_FUNCTION(Py8Collider_VLQ_defaultversion)
    NEEDS_MANAGER(RunMC, MCLoopInfo)
    NEEDS_CLASSES_FROM(Pythia_VLQ, default)
    ALLOW_MODEL(VLQ)
    DEPENDENCY(SpectrumAndDecaysForPythia, SLHAstruct)
    #undef FUNCTION

    #define FUNCTION getPythia_VLQAsBase
    START_FUNCTION(const BaseCollider*)
    NEEDS_MANAGER(RunMC, MCLoopInfo)
    NEEDS_CLASSES_FROM(Pythia_VLQ, default)
    DEPENDENCY(HardScatteringSim, Py8Collider_VLQ_defaultversion)
    ALLOW_MODEL(VLQ)
    #undef FUNCTION

  #undef CAPABILITY


  // Run event generator
  #define CAPABILITY HardScatteringEvent
    #define FUNCTION generateEventPythia_VLQ
    START_FUNCTION(Pythia_VLQ_default::Pythia8::Event)
    NEEDS_MANAGER(RunMC, MCLoopInfo)
    NEEDS_CLASSES_FROM(Pythia_VLQ, default)
    DEPENDENCY(HardScatteringSim, Py8Collider_VLQ_defaultversion)
    ALLOW_MODEL(VLQ)
    #undef FUNCTION

    #define FUNCTION generateEventPythia_VLQ_HEPUtils
    START_FUNCTION(HEPUtils::Event)
    NEEDS_MANAGER(RunMC, MCLoopInfo)
    NEEDS_CLASSES_FROM(Pythia_VLQ, default)
    DEPENDENCY(HardScatteringSim, Py8Collider_VLQ_defaultversion)
    DEPENDENCY(HardScatteringEvent, Pythia_VLQ_default::Pythia8::Event)
    DEPENDENCY(EventWeighterFunction, EventWeighterFunctionType)
    #undef FUNCTION

    #ifndef EXCLUDE_HEPMC
      #define FUNCTION generateEventPythia_VLQ_HepMC
      START_FUNCTION(HepMC3::GenEvent)
      NEEDS_MANAGER(RunMC, MCLoopInfo)
      NEEDS_CLASSES_FROM(Pythia_VLQ, default)
      DEPENDENCY(HardScatteringSim, Py8Collider_VLQ_defaultversion)
      DEPENDENCY(HardScatteringEvent, Pythia_VLQ_default::Pythia8::Event)
      #undef FUNCTION
    #endif

  #undef CAPABILITY


#undef MODULE
