//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Frontend header generated by BOSS for GAMBIT backend ExampleBackendForGAMBIT 1.234.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author The GAMBIT Collaboration
///
///  *********************************************

#include "gambit/Backends/backend_types/ExampleBackendForGAMBIT_1_234/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
  namespace Backends
  {
    namespace ExampleBackendForGAMBIT_1_234
    {
      template <typename T>
      using ClassThree = ::ExampleBackendForGAMBIT_1_234::ClassThree<T>;
      typedef ::ExampleBackendForGAMBIT_1_234::ClassThree__int ClassThree__int;
      typedef ::ExampleBackendForGAMBIT_1_234::ClassFour ClassFour;
      template <class T0>
      using ClassFive = ::ExampleBackendForGAMBIT_1_234::ClassFive<T0>;
      typedef ::ExampleBackendForGAMBIT_1_234::ClassSix ClassSix;
      template <typename T>
      using ClassSeven = ::ExampleBackendForGAMBIT_1_234::ClassSeven<T>;
      typedef ::ExampleBackendForGAMBIT_1_234::ClassSeven__int ClassSeven__int;
      namespace ClassNamespace
      {
        typedef ::ExampleBackendForGAMBIT_1_234::ClassNamespace::ClassEight ClassEight;
      }
      namespace ClassNamespace
      {
        template <class T0>
        using ClassNine = ::ExampleBackendForGAMBIT_1_234::ClassNamespace::ClassNine<T0>;
      }
    }
  }
}

// Functions
BE_FUNCTION(return_as_vector, std::vector<int>, (int, int), "return_as_vector__BOSS_10", "return_as_vector")
BE_FUNCTION(return_as_vector_2, std::vector<int>, (int, int&), "return_as_vector_2__BOSS_11", "return_as_vector_2")
BE_FUNCTION(return_a_ClassFour_instance, ExampleBackendForGAMBIT_1_234::ClassFour, (), "return_a_ClassFour_instance__BOSS_12", "return_a_ClassFour_instance")

// Enums

// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
