//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Frontend header generated by BOSS for GAMBIT backend ExampleBackendForGAMBIT 1.234.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author The GAMBIT Collaboration
///
///  *********************************************

#include "gambit/Backends/backend_types/ExampleBackendForGAMBIT_1_234/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
  namespace Backends
  {
    namespace ExampleBackendForGAMBIT_1_234
    {
      typedef ::ExampleBackendForGAMBIT_1_234::ClassFour ClassFour;
      typedef ::ExampleBackendForGAMBIT_1_234::ClassFive__ClassFour ClassFive__ClassFour;
    }
  }
}

// Functions
BE_FUNCTION(return_as_vector, std::vector<int>, (int, int), "return_as_vector__BOSS_3", "return_as_vector")
BE_FUNCTION(return_as_vector_2, std::vector<int>, (int, int&), "return_as_vector_2__BOSS_4", "return_as_vector_2")
BE_FUNCTION(return_a_ClassFour_instance, ExampleBackendForGAMBIT_1_234::ClassFour, (), "return_a_ClassFour_instance__BOSS_5", "return_a_ClassFour_instance")

// Enums

// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
