//
// Frontend header generated by BOSS for GAMBIT backend gm2calc 1.3.0.
//

#include "gambit/Backends/backend_types/gm2calc_1_3_0/identification.hpp"
#include "gambit/Backends/backend_types/gm2calc_1_3_0/typedefs.hpp"

LOAD_LIBRARY

// Functions
BE_FUNCTION(calculate_amu_1loop, double, (const gm2calc_1_3_0::gm2calc::MSSMNoFV_onshell&), "calculate_amu_1loop__BOSS_10", "calculate_amu_1loop")
BE_FUNCTION(calculate_amu_1loop_non_tan_beta_resummed, double, (const gm2calc_1_3_0::gm2calc::MSSMNoFV_onshell&), "calculate_amu_1loop_non_tan_beta_resummed__BOSS_11", "calculate_amu_1loop_non_tan_beta_resummed")
BE_FUNCTION(calculate_amu_2loop, double, (const gm2calc_1_3_0::gm2calc::MSSMNoFV_onshell&), "calculate_amu_2loop__BOSS_12", "calculate_amu_2loop")
BE_FUNCTION(calculate_amu_2loop_non_tan_beta_resummed, double, (const gm2calc_1_3_0::gm2calc::MSSMNoFV_onshell&), "calculate_amu_2loop_non_tan_beta_resummed__BOSS_13", "calculate_amu_2loop_non_tan_beta_resummed")
BE_FUNCTION(calculate_uncertainty_amu_2loop, double, (const gm2calc_1_3_0::gm2calc::MSSMNoFV_onshell&), "calculate_uncertainty_amu_2loop__BOSS_19", "calculate_uncertainty_amu_2loop")

// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
