//
// Frontend header generated by BOSS for GAMBIT backend HepLike 1.2.
//

#include "gambit/Backends/backend_types/HepLike_1_2/identification.hpp"
#include "gambit/Backends/backend_types/HepLike_1_2/typedefs.hpp"

LOAD_LIBRARY

// Functions

// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
