//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Hand-written frontend header for GAMBIT backend Rivet 4.1.0.
///
///  This used to be generated by BOSS from Rivet's real headers. It is now
///  hand-written against a small shim
///  (Backends/src/frontends/shims/rivet_shim.cpp, compiled into
///  librivet_shim.so by cmake/backends.cmake) that exports a flat,
///  unmangled API covering only the AnalysisHandler methods GAMBIT's
///  ColliderBit module actually calls. See
///  Backends/src/frontends/shims/README.md for the rationale and for what
///  has and has not been verified about this setup (it has not been
///  compiled against a real Rivet install).
///
///  The AnalysisHandler class below is a drop-in replacement for the
///  BOSS-generated wrapper type: ColliderBit_measurements.cpp calls the
///  same method names with the same signatures without modification.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author The GAMBIT Collaboration
///  \date 2026 Oct
///
///  *********************************************

#ifndef EXCLUDE_YODA
#ifndef EXCLUDE_HEPMC

#include "gambit/Backends/backend_types/Rivet_4_1_0/identification.hpp"

LOAD_LIBRARY

#include "gambit/Utils/begin_ignore_warnings_rivet_backend.hpp"
#include "HepMC3/GenEvent.h"
#include "gambit/Utils/end_ignore_warnings.hpp"

#include <string>
#include <utility>
#include <vector>

// Functions exported by librivet_shim.so (Backends/src/frontends/shims/rivet_shim.cpp).
// Plain, unmangled names -- no "__BOSS_" symbol-name candidates needed, since
// these come from an extern "C" shim rather than a mangled C++ symbol.
BE_FUNCTION(rivet_handler_create,               void*, (),                                     "rivet_handler_create",               "rivet_handler_create")
BE_FUNCTION(rivet_handler_destroy,              void,  (void*),                                 "rivet_handler_destroy",              "rivet_handler_destroy")
BE_FUNCTION(rivet_handler_add_analysis,         void,  (void*, const char*),                    "rivet_handler_add_analysis",         "rivet_handler_add_analysis")
BE_FUNCTION(rivet_handler_remove_analyses,      void,  (void*, const char* const*, int),        "rivet_handler_remove_analyses",      "rivet_handler_remove_analyses")
BE_FUNCTION(rivet_handler_num_analysis_names,   int,   (void*),                                 "rivet_handler_num_analysis_names",   "rivet_handler_num_analysis_names")
BE_FUNCTION(rivet_handler_analysis_name,        void,  (void*, int, char*, int),                "rivet_handler_analysis_name",        "rivet_handler_analysis_name")
BE_FUNCTION(rivet_handler_num_std_analysis_names, int, (void*),                                 "rivet_handler_num_std_analysis_names", "rivet_handler_num_std_analysis_names")
BE_FUNCTION(rivet_handler_std_analysis_name,    void,  (void*, int, char*, int),                "rivet_handler_std_analysis_name",    "rivet_handler_std_analysis_name")
// Note: no beamIds()/sqrtS()/runName() -- Rivet::AnalysisHandler has no such
// methods (real names are runBeamIDs()/runSqrtS(), and there is no
// runName()). Those were only called from dead code in
// ColliderBit_measurements.cpp, guarded by a COLLIDERBIT_DEBUG macro that is
// never defined anywhere in this build; see Backends/src/frontends/shims/README.md.
BE_FUNCTION(rivet_handler_nominal_cross_section, double, (void*),                                "rivet_handler_nominal_cross_section", "rivet_handler_nominal_cross_section")
BE_FUNCTION(rivet_handler_analyze,              void,  (void*, HepMC3::GenEvent*),              "rivet_handler_analyze",              "rivet_handler_analyze")
BE_FUNCTION(rivet_handler_finalize,             void,  (void*),                                 "rivet_handler_finalize",             "rivet_handler_finalize")
BE_FUNCTION(rivet_handler_write_data,           void,  (void*, const char*),                    "rivet_handler_write_data",           "rivet_handler_write_data")
BE_FUNCTION(rivet_handler_merge,                void,  (void*, void*),                          "rivet_handler_merge",                "rivet_handler_merge")
BE_FUNCTION(rivet_add_analysis_lib_path,        void,  (const char*),                           "rivet_add_analysis_lib_path",        "rivet_add_analysis_lib_path")

namespace Gambit
{
  namespace Backends
  {
    namespace Rivet_4_1_0
    {
      namespace Rivet
      {
        /// GAMBIT-side stand-in for Rivet::AnalysisHandler, backed by the
        /// rivet_handler_* functions above instead of a BOSS-generated
        /// wrapper/abstract class pair. Exposes exactly the methods
        /// ColliderBit_measurements.cpp calls.
        class AnalysisHandler
        {
          public:
            AnalysisHandler() : handle_(Gambit::Backends::Rivet_4_1_0::rivet_handler_create()) {}

            ~AnalysisHandler()
            {
              Gambit::Backends::Rivet_4_1_0::rivet_handler_destroy(handle_);
            }

            AnalysisHandler(const AnalysisHandler&) = delete;
            AnalysisHandler& operator=(const AnalysisHandler&) = delete;

            void addAnalysis(const std::string& name)
            {
              Gambit::Backends::Rivet_4_1_0::rivet_handler_add_analysis(handle_, name.c_str());
            }

            void removeAnalyses(const std::vector<std::string>& names)
            {
              std::vector<const char*> c;
              c.reserve(names.size());
              for (const auto& n : names) c.push_back(n.c_str());
              Gambit::Backends::Rivet_4_1_0::rivet_handler_remove_analyses(handle_, c.data(), static_cast<int>(c.size()));
            }

            std::vector<std::string> analysisNames() const
            {
              return collectNames(Gambit::Backends::Rivet_4_1_0::rivet_handler_num_analysis_names,
                                   Gambit::Backends::Rivet_4_1_0::rivet_handler_analysis_name);
            }

            std::vector<std::string> stdAnalysisNames() const
            {
              return collectNames(Gambit::Backends::Rivet_4_1_0::rivet_handler_num_std_analysis_names,
                                   Gambit::Backends::Rivet_4_1_0::rivet_handler_std_analysis_name);
            }

            // Note: no beamIds()/sqrtS()/runName() -- see the BE_FUNCTION
            // block above for why.

            double nominalCrossSection() const
            {
              return Gambit::Backends::Rivet_4_1_0::rivet_handler_nominal_cross_section(handle_);
            }

            void analyze(HepMC3::GenEvent& ge)
            {
              Gambit::Backends::Rivet_4_1_0::rivet_handler_analyze(handle_, &ge);
            }

            void finalize()
            {
              Gambit::Backends::Rivet_4_1_0::rivet_handler_finalize(handle_);
            }

            void writeData(const std::string& filename)
            {
              Gambit::Backends::Rivet_4_1_0::rivet_handler_write_data(handle_, filename.c_str());
            }

            void merge(AnalysisHandler& other)
            {
              Gambit::Backends::Rivet_4_1_0::rivet_handler_merge(handle_, other.handle_);
            }

          private:
            template <typename CountFn, typename GetFn>
            std::vector<std::string> collectNames(CountFn count_fn, GetFn get_fn) const
            {
              int n = count_fn(handle_);
              std::vector<std::string> out;
              out.reserve(n);
              char buf[256];
              for (int i = 0; i < n; ++i)
              {
                get_fn(handle_, i, buf, sizeof(buf));
                out.emplace_back(buf);
              }
              return out;
            }

            void* handle_;
        };
      }
    }
  }
}

// Convenience functions (definitions)
namespace Gambit
{
  namespace Backends
  {
    namespace Rivet_4_1_0
    {
      inline void addAnalysisLibPath(const std::string& path)
      {
        rivet_add_analysis_lib_path(path.c_str());
      }
    }
  }
}

// End
#include "gambit/Backends/backend_undefs.hpp"

#endif
#endif
