//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Frontend header generated by BOSS for GAMBIT backend Rivet 4.0.3.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author The GAMBIT Collaboration
///
///  *********************************************

#ifndef EXCLUDE_YODA
#ifndef EXCLUDE_HEPMC

#include "gambit/Backends/backend_types/Rivet_4_0_3/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
  namespace Backends
  {
    namespace Rivet_4_0_3
    {
      namespace Rivet
      {
        typedef ::Rivet_4_0_3::Rivet::AnalysisHandler AnalysisHandler;
      }
    }
  }
}

// Functions
BE_FUNCTION(addAnalysisLibPath, void, (const std::string&), ("addAnalysisLibPath__BOSS_3","_addAnalysisLibPath__BOSS_3"), "addAnalysisLibPath")
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)


// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
 
#endif
#endif
