//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Frontend header generated by BOSS for GAMBIT backend THDMC 1.7.0.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author The GAMBIT Collaboration
///
///  *********************************************

#include "gambit/Backends/backend_types/THDMC_1_7_0/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
    namespace Backends
    {
        namespace THDMC_1_7_0
        {
            typedef ::THDMC_1_7_0::SM SM;
            typedef ::THDMC_1_7_0::THDM THDM;
            typedef ::THDMC_1_7_0::DecayTableTHDM DecayTableTHDM;
            typedef ::THDMC_1_7_0::Constraints Constraints;
        }
    }
}

// Functions
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
