//
// Frontend header generated by BOSS for GAMBIT backend THDMC 1.8.0.
//

#include "gambit/Backends/backend_types/THDMC_1_8_0/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
    namespace Backends
    {
        namespace THDMC_1_8_0
        {
            typedef ::THDMC_1_8_0::SM SM;
            typedef ::THDMC_1_8_0::THDM THDM;
            typedef ::THDMC_1_8_0::DecayTableTHDM DecayTableTHDM;
            typedef ::THDMC_1_8_0::Constraints Constraints;
        }
    }
}

// Functions
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
// - Declared in source file

// Convenience functions (definitions)
BE_CONV_FUNCTION(init_THDM_spectrum_container_CONV, void, (THDM_spectrum_container&, const Spectrum&, int, double, int), "init_THDM_spectrum_container_CONV")

// End
#include "gambit/Backends/backend_undefs.hpp"
