//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Frontend header generated by BOSS for GAMBIT backend THDMC 1.8.0.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author The GAMBIT Collaboration
///
///  *********************************************

#include "gambit/Backends/backend_types/THDMC_1_8_0/identification.hpp"

LOAD_LIBRARY

namespace Gambit
{
    namespace Backends
    {
        namespace THDMC_1_8_0
        {
            typedef ::THDMC_1_8_0::SM SM;
            typedef ::THDMC_1_8_0::THDM THDM;
            typedef ::THDMC_1_8_0::DecayTableTHDM DecayTableTHDM;
            typedef ::THDMC_1_8_0::Constraints Constraints;
        }
    }
}

// Functions
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)
BE_CONV_FUNCTION(init_THDM_spectrum_container_CONV, void, (THDM_spectrum_container&, const Spectrum&, int, double, int), "init_THDM_spectrum_container_CONV")


// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
