--- Makefile	2015-08-28 22:39:35.000000000 +0930
+++ Makefile_patched	2018-04-17 01:07:22.000000000 +0930
@@ -1,28 +1,37 @@
-# Makefile for 2HDMC 
+# Makefile for 2HDMC
 
 # Choose your C++ compiler here (in general g++ on Linux systems):
-CC = g++
-LDFLAGS=-lgsl -lgslcblas
+CC = $(CXX)
 
 #Optimisation level, eg: -O3
 OPT=-O3
 #OR debug level: -g(n=1,2,3)
-DEBUG= 
+DEBUG=
 
-VPATH=src 
-
-CFLAGS= -Wall $(DEBUG) $(OPT)
+LDGSLFLAGS= -lgsl -lgslcblas
+BOSSINCLUDE = -I../../../scripts/BOSS
 
+VPATH=src
 OBJDIR=lib
 LIBDIR=$(OBJDIR)
-SOURCES=THDM.cpp SM.cpp DecayTable.cpp Constraints.cpp Util.cpp runTHDM.cpp
+
+CFLAGS= -Wall $(DEBUG) $(OPT) 
+CFLAGS+= $(CXXFLAGS)
+CFLAGS+= -I$(VPATH) -I$(LIBDIR) -I$(GSLINCLUDE) -I$(BOSSINCLUDE)
+
+
+SOURCES=THDM.cpp SM.cpp DecayTableTHDM.cpp Constraints.cpp Util.cpp runTHDM.cpp BOSS_Constraints.cpp  BOSS_DecayTableTHDM.cpp  BOSS_factory_Constraints.cpp  BOSS_factory_DecayTableTHDM.cpp  BOSS_factory_SM.cpp  BOSS_factory_THDM.cpp  BOSS_SM.cpp  BOSS_THDM.cpp  BOSS_wrapperutils.cpp
 OBJECTS=$(SOURCES:.cpp=.o)
 LIB=lib2HDMC.a
-LDFLAGS+=-L$(LIBDIR) -l2HDMC -lgsl -lgslcblas -lm
+LDFLAGS=-L$(LIBDIR) -l2HDMC $(LDGSLFLAGS) -lm
 #LDFLAGS+=-L$(LIBDIR) -l2HDMC
 LIBS=
 PROG=CalcPhys CalcGen CalcHiggs CalcHybrid CalcHMSSM CalcMSSM CalcInert CalcLH Demo
 
+SHAREDCFLAGS = -fPIC
+SHAREDLIBFLAGS = -Wl,-rpath,$(LIBDIR) -shared -rdynamic $(LDGSLFLAGS)
+SHAREDLIB=lib2HDMC.so
+
 # To use HiggsBounds/HiggsSignals for Higgs constraints, put the corresponding libraries
 # in the "lib" subdirectory and uncomment the following lines.
 # Note that both programs: HiggsBounds (> 4.2.0) and HiggsSignals (> 1.4.0) must be present
@@ -30,12 +39,23 @@
 #LDFLAGS+=-L$(LIBDIR) -lHS -lHB -lgfortran
 #SOURCES+=HBHS.cpp
 
-.PHONY: lib clean distclean
+.PHONY: lib sharedlib clean distclean boss
 
 all: lib $(PROG)
 
 $(OBJDIR)/%.o : %.cpp %.h
-	$(CC) $(CFLAGS) -c $< -o $@
+	$(CC) $(CFLAGS) $(SHAREDCFLAGS) -c $< -o $@
+
+boss:
+	$(CC)  $(CFLAGS) $(SHAREDCFLAGS) -c $(VPATH)/BOSS_Constraints.cpp -o $(LIBDIR)/BOSS_Constraints.o
+	$(CC)  $(CFLAGS) $(SHAREDCFLAGS) -c $(VPATH)/BOSS_DecayTableTHDM.cpp -o $(LIBDIR)/BOSS_DecayTableTHDM.o
+	$(CC)  $(CFLAGS) $(SHAREDCFLAGS) -c $(VPATH)/BOSS_factory_Constraints.cpp -o $(LIBDIR)/BOSS_factory_Constraints.o
+	$(CC)  $(CFLAGS) $(SHAREDCFLAGS) -c $(VPATH)/BOSS_factory_DecayTableTHDM.cpp -o $(LIBDIR)/BOSS_factory_DecayTableTHDM.o
+	$(CC)  $(CFLAGS) $(SHAREDCFLAGS) -c $(VPATH)/BOSS_factory_SM.cpp -o $(LIBDIR)/BOSS_factory_SM.o
+	$(CC)  $(CFLAGS) $(SHAREDCFLAGS) -c $(VPATH)/BOSS_factory_THDM.cpp -o $(LIBDIR)/BOSS_factory_THDM.o
+	$(CC)  $(CFLAGS) $(SHAREDCFLAGS) -c $(VPATH)/BOSS_SM.cpp -o $(LIBDIR)/BOSS_SM.o
+	$(CC)  $(CFLAGS) $(SHAREDCFLAGS) -c $(VPATH)/BOSS_THDM.cpp -o $(LIBDIR)/BOSS_THDM.o
+	$(CC)  $(CFLAGS) $(SHAREDCFLAGS) -c $(VPATH)/BOSS_wrapperutils.cpp -o $(LIBDIR)/BOSS_wrapperutils.o
 
 lib: $(addprefix $(LIBDIR)/, $(LIB))
 
@@ -46,6 +66,24 @@
 %: %.cpp $(addprefix $(LIBDIR)/, $(LIB))
 	@ $(CC) $< -Isrc $(CFLAGS) $(LDFLAGS) $(addprefix $(LIBDIR)/, $(LIBS)) -o $@
 
+sharedlib: $(addprefix $(LIBDIR)/, $(SHAREDLIB))
+
+$(addprefix $(LIBDIR)/, $(SHAREDLIB)): $(addprefix $(OBJDIR)/, $(OBJECTS))
+	@ echo "Making library $@"
+	$(CC) $(addprefix $(OBJDIR)/, $(OBJECTS)) $(SHAREDLIBFLAGS) -o $@
+
+%: %.cpp $(addprefix $(LIBDIR)/, $(SHAREDLIB))
+	@ $(CC) $< -Isrc $(CFLAGS) $(LDFLAGS) $(addprefix $(LIBDIR)/, $(LIBS)) -o $@
+
+sharedlib: $(addprefix $(LIBDIR)/, $(SHAREDLIB))
+
+$(addprefix $(LIBDIR)/, $(SHAREDLIB)): $(addprefix $(OBJDIR)/, $(OBJECTS))
+	@ echo "Making library $@"
+	$(CC) $(addprefix $(OBJDIR)/, $(OBJECTS)) $(SHAREDLIBFLAGS) -o $@
+
+%: %.cpp $(addprefix $(LIBDIR)/, $(SHAREDLIB))
+	@ $(CC) $< -Isrc $(CFLAGS) $(LDFLAGS) $(addprefix $(LIBDIR)/, $(LIBS)) -o $@
+
 clean:
 	@ echo "Cleaning library"
 	@ rm -f $(addprefix $(OBJDIR)/, *.o)
