--- Makefile	2015-08-28 22:09:35.000000000 +0900
+++ Makefile_patched	2019-01-25 21:18:04.000000000 +0900
@@ -1,28 +1,39 @@
-# Makefile for 2HDMC 
+# Makefile for 2HDMC
 
 # Choose your C++ compiler here (in general g++ on Linux systems):
 CC = g++
-LDFLAGS=-lgsl -lgslcblas
+STD = #-std=c++11
 
 #Optimisation level, eg: -O3
 OPT=-O3
 #OR debug level: -g(n=1,2,3)
-DEBUG= 
-
-VPATH=src 
-
-CFLAGS= -Wall $(DEBUG) $(OPT)
+DEBUG=-g
+#Warning level:
+WARNING=-Wall
 
+VPATH=src
 OBJDIR=lib
 LIBDIR=$(OBJDIR)
-SOURCES=THDM.cpp SM.cpp DecayTable.cpp Constraints.cpp Util.cpp runTHDM.cpp
+
+SOURCES=THDM.cpp SM.cpp DecayTableTHDM.cpp Constraints.cpp Util.cpp runTHDM.cpp 
+SOURCES+=BOSS_Constraints.cpp  BOSS_DecayTableTHDM.cpp  BOSS_factory_Constraints.cpp  BOSS_factory_DecayTableTHDM.cpp  BOSS_factory_SM.cpp  BOSS_factory_THDM.cpp  BOSS_SM.cpp  BOSS_THDM.cpp  BOSS_wrapperutils.cpp
 OBJECTS=$(SOURCES:.cpp=.o)
+
+CFLAGS= -Wall $(DEBUG) $(OPT) -I$(VPATH) -I$(LIBDIR) -I$(GSLINCLUDE_DIR)
+
 LIB=lib2HDMC.a
-LDFLAGS+=-L$(LIBDIR) -l2HDMC -lgsl -lgslcblas -lm
-#LDFLAGS+=-L$(LIBDIR) -l2HDMC
+LDFLAGS=$(GSLLIBS) -L$(LIBDIR) -l2HDMC -lm
 LIBS=
 PROG=CalcPhys CalcGen CalcHiggs CalcHybrid CalcHMSSM CalcMSSM CalcInert CalcLH Demo
 
+TEMPINCLUDE = -I../../../scripts/BOSS
+
+SHAREDCFLAGS = -fPIC
+SHAREDLIBFLAGS = -Wl,-rpath,$(LIBDIR) -shared -rdynamic $(GSLLIBS)
+SHAREDLIB=lib2HDMC.so
+
+CFLAGS= $(WARNING) $(STD) $(DEBUG) $(OPT) $(CXXFLAGS) -I$(VPATH) -I$(LIBDIR) -I$(GSLINCLUDE_DIR) $(SHAREDCFLAGS) $(BOSS_INCLUDE) 
+
 # To use HiggsBounds/HiggsSignals for Higgs constraints, put the corresponding libraries
 # in the "lib" subdirectory and uncomment the following lines.
 # Note that both programs: HiggsBounds (> 4.2.0) and HiggsSignals (> 1.4.0) must be present
@@ -30,12 +41,23 @@
 #LDFLAGS+=-L$(LIBDIR) -lHS -lHB -lgfortran
 #SOURCES+=HBHS.cpp
 
-.PHONY: lib clean distclean
+.PHONY: lib sharedlib clean distclean boss
 
 all: lib $(PROG)
 
 $(OBJDIR)/%.o : %.cpp %.h
-	$(CC) $(CFLAGS) -c $< -o $@
+	$(CC) $(CFLAGS) $(SHAREDCFLAGS) $(TEMPINCLUDE) -c $< -o $@
+
+boss:
+	$(CC) $(CFLAGS) -c src/BOSS_Constraints.cpp -o lib/BOSS_Constraints.o
+	$(CC) $(CFLAGS) -c src/BOSS_DecayTableTHDM.cpp -o lib/BOSS_DecayTableTHDM.o
+	$(CC) $(CFLAGS) -c src/BOSS_factory_Constraints.cpp -o lib/BOSS_factory_Constraints.o
+	$(CC) $(CFLAGS) -c src/BOSS_factory_DecayTableTHDM.cpp -o lib/BOSS_factory_DecayTableTHDM.o
+	$(CC) $(CFLAGS) -c src/BOSS_factory_SM.cpp -o lib/BOSS_factory_SM.o
+	$(CC) $(CFLAGS) -c src/BOSS_factory_THDM.cpp -o lib/BOSS_factory_THDM.o
+	$(CC) $(CFLAGS) -c src/BOSS_SM.cpp -o lib/BOSS_SM.o
+	$(CC) $(CFLAGS) -c src/BOSS_THDM.cpp -o lib/BOSS_THDM.o
+	$(CC) $(CFLAGS) -c src/BOSS_wrapperutils.cpp -o lib/BOSS_wrapperutils.o
 
 lib: $(addprefix $(LIBDIR)/, $(LIB))
 
@@ -46,6 +68,15 @@
 %: %.cpp $(addprefix $(LIBDIR)/, $(LIB))
 	@ $(CC) $< -Isrc $(CFLAGS) $(LDFLAGS) $(addprefix $(LIBDIR)/, $(LIBS)) -o $@
 
+sharedlib: $(addprefix $(LIBDIR)/, $(SHAREDLIB))
+
+$(addprefix $(LIBDIR)/, $(SHAREDLIB)): $(addprefix $(OBJDIR)/, $(OBJECTS))
+	@ echo "Making library $@"
+	$(CC) $(addprefix $(OBJDIR)/, $(OBJECTS)) $(SHAREDLIBFLAGS) -o $@
+
+%: %.cpp $(addprefix $(LIBDIR)/, $(SHAREDLIB))
+	@ $(CC) $< -Isrc $(CFLAGS) $(LDFLAGS) $(addprefix $(LIBDIR)/, $(LIBS)) -o $@
+
 clean:
 	@ echo "Cleaning library"
 	@ rm -f $(addprefix $(OBJDIR)/, *.o)
