//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  ColliderPythia typedefs for models in        
///  ColliderBit.                                 
///                                               
///  This file is automatically generated by      
///  collider_harvester.py.  Do not modify.       
///                                               
///  *********************************************
///                                               
///  \author The GAMBIT Collaboration            
///  \date 09:00PM on May 19, 2022
///                                               
///  *********************************************
                                                  
#pragma once                                      
                                                  
#include "gambit/ColliderBit/colliders/ColliderPythia.hpp"
                                                  
namespace Gambit                                  
{                                                 
  namespace ColliderBit                           
  {                                               
                                                  
    /// Typedefs for each Pythia collider         
    /// @{                                        
    typedef ColliderPythia<Pythia_default::Pythia8::Pythia, Pythia_default::Pythia8::Event> ColliderPythia_defaultversion;
    typedef ColliderPythia<Pythia_EM_default::Pythia8::Pythia, Pythia_EM_default::Pythia8::Event> ColliderPythia_EM_defaultversion;
    /// @}

  }
}
