//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Rollcall declarations for module functions
///  contained in SpecBit_NMSSM.cpp
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author Tomas Gonzalo
///          (t.e.gonzalo@fys.uio.no)
///  \date 2018 Oct
///
///  \author Pat Scott
///          (p.scott@imperial.ac.uk)
///  \date 2018 Nov
///
///  *********************************************
///
#ifndef __SpecBit_NMSSM_hpp__
#define __SpecBit_NMSSM_hpp__

// Include this here so that typedef for SLHAstruct gets passed on to standalone codes which use these module functions
//#include "gambit/Elements/slhaea_helpers.hpp"

  /// @{ Functions to supply particle spectra in various forms

  // This capability supplies the physical mass spectrum of the NMSSM plus running
  // parameters in the DRbar scheme. This can be generated by many different
  // constrained models with various boundary conditions, or defined directly.
  #define CAPABILITY NMSSM_spectrum
  START_CAPABILITY

    // =========================
    // NMSSM spectrum (from SARAH-generated SPheno)
    //
    #define FUNCTION get_NMSSM_spectrum_SPheno
    START_FUNCTION(Spectrum)
    ALLOW_MODELS(NMSSM66atQ)
    DEPENDENCY(SMINPUTS, SMInputs)
    BACKEND_REQ(SARAHSPheno_NMSSM_spectrum, (libSPhenoNMSSM), int, (Spectrum&, const Finputs&) )
    BACKEND_OPTION((SARAHSPheno_NMSSM, 4.0.3), (libSPhenoNMSSM))
    BACKEND_OPTION((SARAHSPheno_NMSSMEFT, 4.0.3), (libSPhenoNMSSM))
    #undef FUNCTION

    // ==============================
    // Convert an NMSSM_spectrum into a standard map so that it can be printed
    #define FUNCTION get_NMSSM_spectrum_as_map
    START_FUNCTION(map_str_dbl) // Just a string to double map. Can't have commas in macro input
    DEPENDENCY(NMSSM_spectrum, Spectrum)
    #undef FUNCTION

  #undef CAPABILITY

  /// @}

#endif

