//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Rollcall declarations for module functions
///  contained in SpecBit_NMSSM.cpp
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author Tomas Gonzalo
///          (t.e.gonzalo@fys.uio.no)
///  \date 2018 Oct
///
///  \author Pat Scott
///          (p.scott@imperial.ac.uk)
///  \date 2018 Nov
///
///  \author Sanjay Bloor
///          (sanjay.bloor12@imperial.ac.uk)
///  \date 2019 Jan
///
///  *********************************************
///
#ifndef __SpecBit_NMSSM_hpp__
#define __SpecBit_NMSSM_hpp__

// Include this here so that typedef for SLHAstruct gets passed on to standalone codes which use these module functions
//#include "gambit/Elements/slhaea_helpers.hpp"

  /// @{ Functions to supply particle spectra in various forms

  // This capability supplies the physical mass spectrum of the NMSSM plus running
  // parameters in the DRbar scheme. This can be generated by many different
  // constrained models with various boundary conditions, or defined directly.
  #define CAPABILITY NMSSM_spectrum
  START_CAPABILITY

    // =========================
    // NMSSM spectrum (from SARAH-generated SPheno)
    //
    #define FUNCTION get_NMSSM_spectrum_SPheno
    START_FUNCTION(Spectrum)
    ALLOW_MODELS(NMSSM66atQ)
    DEPENDENCY(SMINPUTS, SMInputs)
    BACKEND_REQ(NMSSM_spectrum, (libSPhenoNMSSM), int, (Spectrum&, const Finputs&) )
    BACKEND_OPTION((SARAHSPheno_NMSSM, 4.0.3), (libSPhenoNMSSM))
    BACKEND_OPTION((SARAHSPheno_NMSSMEFT, 4.0.3), (libSPhenoNMSSM))
    #undef FUNCTION

    // ==============================
    // Convert an NMSSM_spectrum into a standard map so that it can be printed
    #define FUNCTION get_NMSSM_spectrum_as_map
    START_FUNCTION(map_str_dbl) // Just a string to double map. Can't have commas in macro input
    DEPENDENCY(NMSSM_spectrum, Spectrum)
    #undef FUNCTION


  #undef CAPABILITY

  // Generalised Higgs couplings
  #define CAPABILITY Higgs_Couplings

    // From partial widths
    #define FUNCTION NMSSM_higgs_couplings_pwid
    START_FUNCTION(HiggsCouplingsTable)
    DEPENDENCY(NMSSM_spectrum, Spectrum)
    // Use the DecayTable object instead of each individual decay channel... this may need to change if 
    // we plan to use tools other than SPheno, but the YAML file should be able to steer this.
    DEPENDENCY(decay_rates, DecayTable)
    DEPENDENCY(Reference_SM_Higgs_decay_rates, DecayTable::Entry)
    DEPENDENCY(Reference_SM_other_Higgs_decay_rates, DecayTable::Entry)
    DEPENDENCY(Reference_SM_h0_3_decay_rates, DecayTable::Entry)
    DEPENDENCY(Reference_SM_A0_decay_rates, DecayTable::Entry)
    DEPENDENCY(Reference_SM_A0_2_decay_rates, DecayTable::Entry)
    // DEPENDENCY(Higgs_decay_rates, DecayTable::Entry)
    // DEPENDENCY(h0_2_decay_rates, DecayTable::Entry)
    // DEPENDENCY(A0_decay_rates, DecayTable::Entry)
    // DEPENDENCY(H_plus_decay_rates, DecayTable::Entry)
    DEPENDENCY(t_decay_rates, DecayTable::Entry)
    ALLOW_MODELS(NMSSM66atQ)
    #undef FUNCTION

  #undef CAPABILITY

  /// @}

#endif

