//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Explicit functor template class              
///  instantiations needed by standalone program  
///  CBS.                          
///                                               
///  This file was automatically generated by     
///  standalone_facilitator.py. Do not modify.    
///  The content is harvested from the rollcall   
///  headers registered in module_rollcall.hpp    
///  and the types registered in                  
///  types_rollcall.hpp.                          
///                                               
///  *********************************************
///                                               
///  Authors:                                     
///                                               
///  \author The GAMBIT Collaboration            
///  \date 04:12PM on July 31, 2024
///                                               
///  *********************************************
                                                  
#include "gambit/Elements/functor_definitions.hpp"
#include "gambit/Elements/types_rollcall.hpp"   
#include "gambit/Backends/backend_functor_types.hpp"
                                                  
namespace Gambit                                  
{                                                 
  // Non-module types                             
  template class module_functor<void>;            
  template class module_functor<NREO_DM_nucleon_couplings>;
  template class module_functor<GalacticHaloProperties>;
  template class module_functor<DD_coupling_container>;
  template class module_functor<DarkAges::Energy_injection_spectrum>;
  template class module_functor<HepMC3::GenEvent>;
  template class module_functor<BBN_container>;
  template class module_functor<std::set<std::string>>;
  template class module_functor<unsigned>;
  template class module_functor<dbl_dbl_bool>;
  template class module_functor<LocalMaxwellianHalo>;
  template class module_functor<daFunk::Funk>;
  template class module_functor<DarkAges::Energy_injection_efficiency_table>;
  template class module_functor<ModelParameters>;
  template class module_functor<mass_es_pseudonyms>;
  template class module_functor<HiggsCouplingsTable>;
  template class module_functor<fptr_dd>;
  template class module_functor<Pythia_8_212::Pythia8::Event>;
  template class module_functor<map_str_str>;
  template class module_functor<std::vector<std::vector<double>>>;
  template class module_functor<DecayTable>;
  template class module_functor<Classy_input>;
  template class module_functor<Contur_output>;
  template class module_functor<hb_ModelParameters>;
  template class module_functor<parameters>;
  template class module_functor<ddpair>;
  template class module_functor<std::shared_ptr<std::ostringstream>>;
  template class module_functor<std::string>;
  template class module_functor<float>;
  template class module_functor<std::vector<float>>;
  template class module_functor<pybind11::dict>;
  template class module_functor<SpecBit::SpectrumEntriesForVevacious>;
  template class module_functor<Multimode_inputs>;
  template class module_functor<fh_MSSMMassObs_container>;
  template class module_functor<DM_nucleon_couplings>;
  template class module_functor<double>;
  template class module_functor<std::vector<double>>;
  template class module_functor<map_int_triplet_dbl>;
  template class module_functor<Spectrum>;
  template class module_functor<DecayTable::Entry>;
  template class module_functor<fptr>;
  template class module_functor<flav_prediction>;
  template class module_functor<int>;
  template class module_functor<WIMPprops>;
  template class module_functor<SLHAstruct>;
  template class module_functor<std::vector<int>>;
  template class module_functor<fh_HiggsProd_container>;
  template class module_functor<fh_FlavourObs_container>;
  template class module_functor<bool>;
  template class module_functor<SMInputs>;
  template class module_functor<HEPUtils::Event>;
  template class module_functor<fh_Couplings_container>;
  template class module_functor<Eigen::Matrix3cd>;
  template class module_functor<const SubSpectrum*>;
  template class module_functor<Multi_Contur_output>;
  template class module_functor<map_intpair_dbl>;
  template class module_functor<fh_HiggsMassObs_container>;
  template class module_functor<map_str_dbl>;
  template class module_functor<SpecBit::VevaciousResultContainer>;
  template class module_functor<triplet<double>>;
  template class module_functor<fh_PrecisionObs_container>;
  template class module_functor<nuisance>;
  // Module types
  template class module_functor<const ColliderBit::BaseCollider*>;
  template class module_functor<ColliderBit::map_int_process_xsec>;
  template class module_functor<ColliderBit::xsec_container>;
  template class module_functor<ColliderBit::map_str_AnalysisLogLikes>;
  template class module_functor<ColliderBit::map_PID_pair_PID_pair_xsec>;
  template class module_functor<ColliderBit::vec_PID_pair>;
  template class module_functor<ColliderBit::pair_str_SLHAstruct>;
  template class module_functor<ColliderBit::BaseDetector*>;
  template class module_functor<ColliderBit::multimap_int_PID_pair>;
  template class module_functor<ColliderBit::Py8Collider_defaultversion>;
  template class module_functor<ColliderBit::AnalysisDataPointers>;
  template class module_functor<ColliderBit::MCLoopInfo>;
  template class module_functor<ColliderBit::MC_xsec_container>;
  template class module_functor<ColliderBit::EventWeighterFunctionType>;
  template class module_functor<ColliderBit::AnalysisContainer>;
}

// Define standalone versions of functor signal helpers (that do nothing)
namespace Gambit                                                      
{                                                                     
  namespace FunctorHelp                                               
  {                                                                   
    void check_for_shutdown_signal(module_functor_common&) {}         
    bool emergency_shutdown_begun() { return false; }                 
    void entering_multithreaded_region(module_functor_common&) {}     
    void leaving_multithreaded_region(module_functor_common&) {}      
  }                                                                   
}
