//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Explicit functor template class              
///  instantiations needed by standalone program  
///  CBS.                          
///                                               
///  This file was automatically generated by     
///  standalone_facilitator.py. Do not modify.    
///  The content is harvested from the rollcall   
///  headers registered in module_rollcall.hpp    
///  and the types registered in                  
///  types_rollcall.hpp.                          
///                                               
///  *********************************************
///                                               
///  Authors:                                     
///                                               
///  \author The GAMBIT Collaboration            
///  \date 09:56AM on June 12, 2026
///                                               
///  *********************************************
                                                  
#include "gambit/Elements/functor_definitions.hpp"
#include "gambit/Elements/types_rollcall.hpp"   
#include "gambit/Backends/backend_functor_types.hpp"
                                                  
namespace Gambit                                  
{                                                 
  // Non-module types                             
  template class module_functor<void>;            
  template class module_functor<Contur_output>;
  template class module_functor<DecayTable>;
  template class module_functor<DecayTable::Entry>;
  template class module_functor<HEPUtils::Event>;
  template class module_functor<HepMC3::GenEvent>;
  template class module_functor<HiggsCouplingsTable>;
  template class module_functor<ModelParameters>;
  template class module_functor<Multi_Contur_output>;
  template class module_functor<Pythia_8_312::Pythia8::Event>;
  template class module_functor<SLHAstruct>;
  template class module_functor<SMInputs>;
  template class module_functor<Spectrum>;
  template class module_functor<bool>;
  template class module_functor<double>;
  template class module_functor<fh_HiggsProd_container>;
  template class module_functor<float>;
  template class module_functor<fptr>;
  template class module_functor<hb_ModelParameters>;
  template class module_functor<int>;
  template class module_functor<map_str_dbl>;
  template class module_functor<map_str_str>;
  template class module_functor<mass_es_pseudonyms>;
  template class module_functor<std::shared_ptr<std::ostringstream>>;
  template class module_functor<std::string>;
  template class module_functor<std::vector<double>>;
  template class module_functor<std::vector<float>>;
  template class module_functor<std::vector<int>>;
  template class module_functor<triplet<double>>;
  template class module_functor<unsigned>;
  // Module types
  template class module_functor<ColliderBit::AnalysisContainer>;
  template class module_functor<ColliderBit::AnalysisDataPointers>;
  template class module_functor<ColliderBit::BaseDetector*>;
  template class module_functor<ColliderBit::EventWeighterFunctionType>;
  template class module_functor<ColliderBit::MCLoopInfo>;
  template class module_functor<ColliderBit::MC_xsec_container>;
  template class module_functor<ColliderBit::Py8Collider_defaultversion>;
  template class module_functor<ColliderBit::initialxsec_container>;
  template class module_functor<ColliderBit::map_PID_pair_PID_pair_xsec>;
  template class module_functor<ColliderBit::map_int_process_xsec>;
  template class module_functor<ColliderBit::map_str_AnalysisLogLikes>;
  template class module_functor<ColliderBit::map_str_map_int_process_xsec>;
  template class module_functor<ColliderBit::map_str_xsec_container>;
  template class module_functor<ColliderBit::multimap_int_PID_pair>;
  template class module_functor<ColliderBit::pair_str_SLHAstruct>;
  template class module_functor<ColliderBit::vec_PID_pair>;
  template class module_functor<ColliderBit::xsec_container>;
  template class module_functor<const ColliderBit::BaseCollider*>;
}

// Define standalone versions of functor signal helpers (that do nothing)
namespace Gambit                                                      
{                                                                     
  namespace FunctorHelp                                               
  {                                                                   
    void check_for_shutdown_signal(module_functor_common&) {}         
    bool emergency_shutdown_begun() { return false; }                 
    void entering_multithreaded_region(module_functor_common&) {}     
    void leaving_multithreaded_region(module_functor_common&) {}      
  }                                                                   
}
