##########################################################################
## GAMBIT configuration for the following                               ##
##                                                                      ##
## Models: THDM, THDMI, THDMII, THDMLS, THDMflipped                     ##
##                                                                      ##
## Includes all compatible likelihoods:                                 ##
## theoretical, collider, electroweak, flavour                          ##
##                                                                      ##
## Requires backends:                                                   ##
## thdmc, SuperISO, HiggsBounds, HiggsSignals, HEPLike                  ##
##                                                                      ##
## Author: A.S. Woodcock                                                ##
## Date: 22/JUL/2022                                                    ##
##                                                                      ##
##########################################################################

Parameters:
    StandardModel_SLHA2: !import include/StandardModel_SLHA2_defaults.yaml

    THDMIIatQ:

      m12_2:
          prior_type: none
      tanb:
          prior_type: none
      lambda1:
          prior_type: none
      lambda2:
          prior_type: none
      lambda3:
          prior_type: none
      lambda4:
          prior_type: none
      lambda5:
          prior_type: none
      lambda6:
          prior_type: none
      lambda7:
          prior_type: none
      Qin:
          prior_type: none


#################################
##     PRINTER SELECTION       ##
#################################


Printer:

  # printer: cout

  # printer: ascii
  # options:
  #   buffer_length: 100
  #   output_file: "scan.txt"

  # printer: hdf5
  # options:
  #   output_file: "scan.hdf5"
  #   group: "/data"
  #   delete_file_on_restart: true

  printer: hdf5_v1
  options:
    output_file: "scan.hdf5"
    group: "/data"
    delete_file_on_restart: true
    disable_combine_routines: true


#################################
##     SCANNER SELECTION       ##
#################################

Scanner:

  use_scanner: postprocessor

  scanners:

    postprocessor:
      plugin: postprocessor
      version: "1.0" # If you want to use v1 of the postprocessor, select it here (default is currently v2.0)
      # Turn off extra log output to track what the postprocessor is doing (won't be output unless debug: true anyway though)
      verbose_logging: false
      # Name of the new global likelihood contribution.
      like: LogLike
      # Name of the combined new+old likelihood
      reweighted_like: Comb_LogLike
      # Add LogLike in the old output to New_LogLike in the new output.
      add_to_like: [LogLike]
      # Allow overwriting of the old output with the new output (e.g. if you would rather name New_LogLike as LogLike)
      permit_discard_old_likes: true
      update_interval: 1000 # Frequency to print status update message
      batch_size: 100 # Number of points to distribute to worker processes each time they request more work
       # Throw away all points outside the cuts
      discard_points_outside_cuts: false
      # Information about input dataset to be postprocessed
      reader:
        type: hdf5
        file: "test.hdf5"
        group: "/data"


#################################
##  OBSERVABLES / LIKELIHOODS  ##
#################################


ObsLikes:

  #-------------------------------------#
  #      THEORETICAL LIKELIHOODS        #
  #-------------------------------------#

  # simple theory constraints applied BEFORE spectrum generation
  - purpose: LogLike
    capability: basic_theory_LogLikelihood_THDM

  # # 1-loop vacuum meta-stability Likelihood using Vevacious
  # - purpose: LogLike
  #   capability: VS_likelihood
  #   sub_capabilities:
  #     global: [quantum]
  #     nearest: [quantum]

  # check if we can run spectrum without error
  - purpose: LogLike
    capability: runToScaleTest_LogLikelihood_THDM

  # Checks that the LO or NLO S-matrix is unitary
  #- purpose: LogLike
    #capability: unitarity_LogLikelihood_THDM
    #function: NLO_unitarity_LogLikelihood_THDM

  # Checks that the LO or NLO S-matrix is unitary
  #- purpose: LogLike
    #capability: unitarity_LogLikelihood_THDM
    #function: LO_unitarity_LogLikelihood_THDM

  # guides scanner towards mh = 125 GeV
  #- purpose: LogLike
    #capability: higgs_exp_mass_LogLikelihood_THDM

  # only keeps points that correspond to regular Higgs scenario
  #- purpose: LogLike
    #capability: higgs_scenario_LogLikelihood_THDM

  # Stability + meta-stability of the 2HDM Potential
  #- purpose: LogLike
    #capability: stability_LogLikelihood_THDM

  # Perturbativity check of scalar mass corrections
  #- purpose: LogLike
    #capability: scalar_mass_corrections_LogLikelihood_THDM

  # Perturbativity check of scalar couplings
  #- purpose: LogLike
    #capability: perturbativity_LogLikelihood_THDM
    # #function: perturbativity_lambdas_LogLikelihood_THDM
    #function: perturbativity_LogLikelihood_THDM

  # Perturbativity check of yukawa couplings
  #- purpose: LogLike
    #capability: perturbativity_yukawas_LogLikelihood_THDM
    
  #-------------------------------------#
  #      COLLIDER LIKELIHOODS           #
  #-------------------------------------#

  # HiggsSignals 2.5.0 likelihood
  #- purpose: LogLike
    #capability: LHC_Higgs_LogLike
    #function: calc_HS_2_LHC_LogLike

  # HiggsBounds 5.8.0 likelihood
  #- purpose: LogLike
    #capability: LEP_Higgs_LogLike
    #function: calc_HB_5_LEP_LogLike

  #-------------------------------------#
  #      PRECISION LIKELIHOODS          #
  #-------------------------------------#

  # Calculates the electroweak precision parameters, S, T, U, V, W, X
  # & fits to meausured values. S, T, U involve a correlation matrix.
  # Includes low-energy notation described in arxiv::9407203.
  # Likelihood type: Half-Gaussian
  #- purpose:    LogLike
    #capability: oblique_parameters_LogLikelihood

  # muon anomalous magnetic moment likelihood (for GTHDM)
  #- purpose: LogLike
    #capability: lnL_gm2
    #function: lnL_gm2

  #-------------------------------------#
  #      FLAVOR LIKELIHOODS             #
  #-------------------------------------#

  # ------------------------- #
  # B -> Xs gamma likelihoods #
  # ------------------------- #

  #- purpose:    LogLike
    #capability: b2sgamma_LogLikelihood
  #- purpose:    LogLike
    #capability: B2Kstargamma_LogLikelihood

  # ---------------------- #
  # B -> mu mu likelihoods #
  # ---------------------- #

  #- purpose:    LogLike
    #capability: B2mumu_LogLikelihood_Atlas
    #sub_capabilities: [BRuntag_Bsmumu, BR_Bdmumu]
  #- purpose:    LogLike
    #capability: B2mumu_LogLikelihood_LHCb
    #sub_capabilities: [BRuntag_Bsmumu, BR_Bdmumu]
  #- purpose:    LogLike
    #capability: B2mumu_LogLikelihood_CMS
    #sub_capabilities: [BRuntag_Bsmumu, BR_Bdmumu]

  # ------------------------ #
  # B -> K mu mu likelihoods #
  # ------------------------ #

  #- purpose:    LogLike
    #capability: Bd2KmumuBr_LogLikelihood_LHCb #new
  #- purpose:    LogLike
    #capability: Bd2KmumuBr_LogLikelihood_Belle #new
  #- purpose:    LogLike
    #capability: B2KmumuBr_LogLikelihood_LHCb
  #- purpose:    LogLike
    #capability: B2KmumuBr_LogLikelihood_CMS #new
  #- purpose:    LogLike
    #capability: B2KmumuBr_LogLikelihood_Belle #new

  # ---------------------- #
  # B -> K e e likelihoods #
  # ---------------------- #

  #- purpose:    LogLike
    #capability: B2KeeBr_LogLikelihood_Belle #new
  #- purpose:    LogLike
    #capability: Bd2KeeBr_LogLikelihood_Belle #new

  # ------------------------- #
  # B -> K* mu mu likelihoods #
  # ------------------------- #

  #- purpose:    LogLike
    #capability: B2KstarmumuAng_LogLikelihood_Atlas
    #sub_capabilities: [FL, S3, S4, S5, S7, S8]
  #- purpose:    LogLike
    #capability: B2KstarmumuAng_LogLikelihood_CMS
    #sub_capabilities: [P1, P5prime]
  #- purpose:    LogLike
    #capability: B2KstarmumuAng_LogLikelihood_Belle
    #sub_capabilities: [P4prime, P5prime]
  #- purpose:    LogLike
    #capability: B2KstarmumuAng_LogLikelihood_LHCb_2020
    #sub_capabilities: [FL, AFB, S3, S4, S5, S7, S8, S9]
  #- purpose:    LogLike
    #capability: Bu2KstarmumuAng_LogLikelihood_LHCb_2020
    #sub_capabilities: [FL, AFB, S3, S4, S5, S7, S8, S9]
  #- purpose:    LogLike
    #capability: B2KstarmumuBr_LogLikelihood_LHCb
  #- purpose:    LogLike
    #capability: Bs2phimumuBr_LogLikelihood
  #- purpose:    LogLike
    #capability: B2KstarmumuAng_CPAssym_LogLikelihood_LHCb #new
  #- purpose:    LogLike
    #capability: B2KstarellellAng_LogLikelihood_Belle
    #sub_capabilities: [P4prime, P5prime]

  # ----------------------- #
  # B -> K* e e likelihoods #
  # ----------------------- #

  #- purpose:    LogLike
    #capability: B2KstareeAng_Lowq2_LogLikelihood_LHCb_2020
    #sub_capabilities: [FLee, AT_Re, AT_2, AT_Im]

  # ---------------------- #
  # RK and RK* likelihoods #
  # ---------------------- #

  #- purpose: LogLike # OFF - NOT EXPLAINED BY 2HDM
    #capability: RKRKstar_LogLikelihood_LHCb
    #sub_capabilities: [RK, RKstar]
  #- purpose: LogLike # OFF - NOT EXPLAINED BY 2HDM
    #capability: RK_LogLikelihood_CMS #new
  #- purpose: LogLike # OFF - NOT EXPLAINED BY 2HDM
    #capability: RK_LogLikelihood_Belle #new

  # ------------------------ #
  # B -> K nu nu likelihoods #
  # ------------------------ #

  #- purpose: LogLike
    #capability: BKnunu_LogLikelihood_Belle_sl #new
  #- purpose: LogLike
    #capability: BKnunu_LogLikelihood_Belle_had #new
  #- purpose: LogLike
    #capability: BuKnunu_LogLikelihood_Belle_sl #new
  #- purpose: LogLike
    #capability: BuKnunu_LogLikelihood_Belle_had #new
  #- purpose: LogLike
    #capability: BuKnunu_LogLikelihood_BelleII #new
  #- purpose: LogLike
    #capability: BKnunu_LogLikelihood_BaBar #new
  #- purpose: LogLike
    #capability: BuKnunu_LogLikelihood_BaBar #new
  # #- purpose: LogLike
  #   #capability: BKstarnunu_LogLikelihood_Belle_sl # missing prediction_B2Kstarnunu #new
  # #- purpose: LogLike
  #   #capability: BKstarnunu_LogLikelihood_Belle_had # missing prediction_B2Kstarnunu #new
  # #- purpose: LogLike
  #   #capability: BuKstarnunu_LogLikelihood_Belle_sl # missing prediction_Bu2Kstarnunu #new
  # #- purpose: LogLike
  #   #capability: BuKstarnunu_LogLikelihood_Belle_had # missing prediction_Bu2Kstarnunu #new
  # #- purpose: LogLike
  #   #capability: BKstarnunu_LogLikelihood_BaBar # missing prediction_B2Kstarnunu #new
  # #- purpose: LogLike
  #   #capability: BuKstarnunu_LogLikelihood_BaBar # missing prediction_Bu2Kstarnunu #new

  # ----------------------------- #
  # Semileptonic FCCC likelihoods #
  # ----------------------------- #

  #- purpose:    LogLike
    #capability: SL_LogLikelihood  # OFF - RD, RDstar, Rmu, RDemu
    #sub_capabilities: [BDmunu, BDstarmunu, Btaunu, Dstaunu, DSmunu, Dmunu, Dtaunu]
  #- purpose:    LogLike # DOES NOTHING
    #capability: FLDstar_LogLikelihood
  #- purpose:    LogLike # DOES NOTHING
    #capability: dBRBDstartaunu_LogLikelihood
  #- purpose:    LogLike # DOES NOTHING
    #capability: dBRBDtaunu_LogLikelihood

  # --------------------------------- #
  # Lifetime and Delta MB likelihoods #
  # --------------------------------- #

  #- purpose:    LogLike
    #capability: Bc_lifetime_LogLikelihood
  #- purpose:    LogLike
    #capability: Delta_MBs_LogLikelihood
  #- purpose:    LogLike
    #capability: Delta_MBd_LogLikelihood

  # ------------------------------------ #
  # Lepton flavour violating likelihoods #
  # ------------------------------------ #

  #- purpose:    LogLike  # DOES NOTHING
    #capability: l2lgamma_LogLikelihood
  #- purpose:    LogLike  # DOES NOTHING
    #capability: l2lll_LogLikelihood
  #- purpose:    LogLike # PROBABLY DOES NOTHING
    #capability: h2ltau_LogLikelihood #new

  # --------------------------------------- #
  # Flavour violating top decay likelihoods #
  # --------------------------------------- #
  
  #- purpose:    LogLike # DOES NOTHING
    #capability: t2ch_LogLikelihood
  #- purpose:    LogLike # PROBABLY DOES NOTHING
    #capability: t2bbc_LogLikelihood #new
  #- purpose:    LogLike # PROBABLY DOES NOTHING
    #capability: t2mutauc_LogLikelihood #new
  #- purpose:    LogLike # PROBABLY DOES NOTHING
    #capability: Bc2taunu_LogLikelihood #new
  #- purpose:    LogLike
    #capability: Bs2ll_LogLikelihood
  #- purpose:    LogLike
    #capability: B2Kll_LogLikelihood

  # --------------------------------------- #
  #              Other                      #
  # --------------------------------------- #

  #- purpose:    LogLike
    #capability: B2Xsnunu_LogLikelihood
  #- purpose:    LogLike # DOES NOTHING
    #capability: gmu_ge_LogLikelihood

#################################
##          OBSERVABLES        ##
#################################


  # entire 2HDM spectrum
  - capability: THDM_spectrum
    type: map_str_dbl
    purpose: Observable

  # # 2HDM decay rates and branching ratios 
  # - capability: all_BFs
  #   purpose: Observable


  #  ---- Electroweak Observables ----

  #- purpose:      Observable
    #capability:   prediction_Tpar

  #- purpose:      Observable
    #capability:   prediction_Spar

  #- purpose:      Observable
    #capability:   prediction_Upar


  #  ---- Flavor Observables ----

  #  ---- Wilson Coefficients ----

  # - purpose: Observable
  #   capability: DeltaCQ1

  # - purpose: Observable
  #   capability: DeltaCQ1_Prime

  # - purpose: Observable
  #   capability: DeltaCQ2

  # - purpose: Observable
  #   capability: DeltaCQ2_Prime

  # - purpose: Observable
  #   capability: DeltaCQ1_tautau

  # - purpose: Observable
  #   capability: DeltaCQ1_tautau_Prime

  # - purpose: Observable
  #   capability: DeltaCQ2_tautau

  # - purpose: Observable
  #   capability: DeltaCQ2_tautau_Prime

  # - purpose: Observable
  #   capability: DeltaC2

  # - purpose: Observable
  #   capability: DeltaC7

  # - purpose: Observable
  #   capability: DeltaC7_Prime

  # - purpose: Observable
  #   capability: DeltaC8

  # - purpose: Observable
  #   capability: DeltaC8_Prime

  # - purpose: Observable
  #   capability: DeltaC9

  # - purpose: Observable
  #   capability: DeltaC9_Prime

  # - purpose: Observable
  #   capability: DeltaC10

  # - purpose: Observable
  #   capability: DeltaC10_Prime

  # - purpose: Observable
  #   capability: DeltaC9_tautau

  # - purpose: Observable
  #   capability: DeltaC9_tautau_Prime

  # - purpose: Observable
  #   capability: DeltaC10_tautau

  # - purpose: Observable
  #   capability: DeltaC10_tautau_Prime


###################################
##  Likelihood/Observable Rules  ##
###################################


Rules:

  - capability: couplingtable_THDM
    function: get_coupling_table_using_Higgs_basis

  - capability: basic_theory_LogLikelihood_THDM
    options:
      only_perturbativity: false

  - capability: runToScaleTest_LogLikelihood_THDM
    options:
      check_other_scale: 1000
      hard_cutoff: true

  - capability: perturbativity_LogLikelihood_THDM
    options:
      check_other_scale: [-1, 1000]
      skipCubicCouplings: true
      skipGoldstoneCouplings: true
      hard_cutoff: false

  - capability: perturbativity_yukawas_LogLikelihood_THDM
    options:
      check_other_scale: [-1, 1000]
      hard_cutoff: false

  - capability: scalar_mass_corrections_LogLikelihood_THDM
    options:
      check_other_scale: [-1, 1000]
      hard_cutoff: false

  - capability: stability_LogLikelihood_THDM
    options:
      check_other_scale: [-1, 1000]
      check_metastability: false
      hard_cutoff: false

  - capability: unitarity_LogLikelihood_THDM
    options:
      check_other_scale: [1000]
      # options below only for NLO unitarity
      check_correction_ratio: true
      wave_function_corrections: false
      gauge_corrections: true
      yukawa_corrections: true
      hard_cutoff: false

  - capability: higgs_exp_mass_LogLikelihood_THDM
    options:
      higgs_mass_uncertainty: 5.0
      valid_range: 200
      hard_cutoff: false

  - capability: higgs_scenario_LogLikelihood_THDM
    options:
      hidden_higgs_scenario: false

  - capability: THDM_spectrum
    type: map_str_dbl
    options:
      print_minimal_yukawas: true
      print_running_masses: true

  - capability: decay_rates
    function: all_decays

  - capability: all_BFs
    function: get_decaytable_as_map
    options:
      skip_particles: ['H-','W+','W-','Z0','e+_2','e+_3','e-_2','e-_3','mu+','mu-','pi+','pi-','pi0','tau+','tau-','tbar','u_3','ubar_3']
      print_BF_error: False
      print_as_widths: True

  - capability: Higgs_Couplings
    # function: THDM_higgs_couplings_pwid
    function: THDM_higgs_couplings_2HDMC

  - capability: prediction_DeltaMs
    function: SuperIso_prediction_Delta_MBs

  - capability: RK_LogLikelihood_LHCb
    function: RK_LogLikelihood_LHCb

  - capability: RKstar_LogLikelihood_LHCb
    function: RKstar_LogLikelihood_LHCb

  - capability: prediction_Tpar
    function: STUVWX_to_prediction_Tpar

  - capability: prediction_Spar
    function: STUVWX_to_prediction_Spar

  - capability: prediction_Upar
    function: STUVWX_to_prediction_Upar

  - capability: prediction_STUVWX
    function: THDMC_prediction_STUVWX

  - capability: Reference_SM_Higgs_decay_rates
    function: Ref_SM_Higgs_decays_THDM

  - capability: Reference_SM_other_Higgs_decay_rates
    function: Ref_SM_other_Higgs_decays_THDM

  - capability: Reference_SM_A0_decay_rates
    function: Ref_SM_A0_decays_THDM

  - capability: t_decay_rates
    function: t_decays_THDM

  - capability: prediction_b2sgamma
    function: SuperIso_prediction_b2sgamma

  - capability: prediction_B2mumu
    function: SuperIso_prediction_B2mumu

  - capability: B2KstarmumuAng_LogLikelihood_Atlas
    function: HEPLike_B2KstarmumuAng_LogLikelihood_Atlas
    options:
      ignore_lowq2_bin: true

  - capability: B2KstarmumuAng_LogLikelihood_Belle
    function: HEPLike_B2KstarmumuAng_LogLikelihood_Belle
    options:
      ignore_lowq2_bin: true

  - capability: B2KstarmumuAng_LogLikelihood_LHCb_2020
    function: HEPLike_B2KstarmumuAng_LogLikelihood_LHCb_2020
    options:
      ignore_lowq2_bin: true

  - capability: B2KstarmumuBr_LogLikelihood_LHCb
    function: HEPLike_B2KstarmumuBr_LogLikelihood_LHCb
    options:
      ignore_lowq2_bin: true

  - capability: muon_gm2
    # function: SuperIso_muon_gm2
    function: THDM_mumugamma

  - capability: muon_gm2_SM
    function: gm2_SM_ee

  - capability: muon_gm2_Exp
    function: gm2_Exp_BNL

  - capability: LHC_Higgs_LogLike
    options:
      # -1:all, 0:RUN1_SS, 1:LATEST_SS, 2:LATEST_STXS
      HS_analysis: -1

#########################
# Logging setup
#########################


Logger:

  redirection:
    # [Debug] :  "debug.log"
    [Default] :  "default.log"
    [DecayBit] :  "DecayBit.log"
    [PrecisionBit] :  "PrecisionBit.log"
    [ColliderBit] :  "ColliderBit.log"
    [SpecBit] :  "SpecBit.log"

##########################
# Name/Value Section
##########################

KeyValues:

  print_scanID: false

  likelihood:
    print_invalid_points: false
    model_invalid_for_lnlike_below: -1e6
    model_invalid_for_lnlike_below_alt: -5e5
    disable_print_for_lnlike_below: -3e4
    debug: false

  dependency_resolution:
    prefer_model_specific_functions: true
    use_old_routines: false
    unused_rule_is_an_error: false

  exceptions:
    dependency_resolver_error: fatal
    dependency_resolver_warning: non-fatal
    core_warning: fatal

  default_output_path: "runs/PP/"
  debug: false
