disabled:
  DarkSUSY:
  - 5.1.3
  DarkSUSY_MSSM:
  - 6.2.5
  FeynHiggs:
  - 2.11.2
  - 2.11.3
  - 2.12.0
  LibMathematicaTest:
  - '1.0'
  SUSYHD:
  - 1.0.2
enabled:
  ATLAS_FullLikes:
  - '1.0'
  Acropolis:
  - 1.2.1
  AlterBBN:
  - '2.2'
  CalcHEP:
  - 3.6.27
  CaptnGeneral:
  - '2.1'
  Contur:
  - 3.0.0
  DDCalc:
  - 1.0.0
  - 1.1.0
  - 1.2.0
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  DarkAges:
  - 1.2.0
  DarkCast:
  - '1.1'
  DarkSUSY_MSSM:
  - 6.1.1
  - 6.2.2
  - 6.4.0
  DarkSUSY_generic_wimp:
  - 6.1.1
  - 6.2.2
  - 6.2.5
  - 6.4.0
  DirectDM:
  - 2.2.0
  HepLike:
  - '2.0'
  HepLikeData:
  - '1.4'
  HiggsBounds:
  - 4.2.1
  - 4.3.1
  HiggsSignals:
  - '1.4'
  LibFarrayTest:
  - '1.0'
  LibFirst:
  - '1.0'
  - '1.1'
  LibFortran:
  - '1.0'
  LibSecond:
  - '1.1'
  - '1.2'
  LibThird:
  - '1.1'
  - '1.2'
  MicrOmegas_DMsimpVectorMedVectorDM:
  - 3.6.9.2
  MicrOmegas_DiracSingletDM_Z2:
  - 3.6.9.2
  MicrOmegas_MSSM:
  - 3.6.9.2
  MicrOmegas_MajoranaSingletDM_Z2:
  - 3.6.9.2
  MicrOmegas_ScalarSingletDM_Z2:
  - 3.6.9.2
  MicrOmegas_ScalarSingletDM_Z3:
  - 3.6.9.2
  MicrOmegas_VectorSingletDM_Z2:
  - 3.6.9.2
  MontePythonLike:
  - 3.3.0
  - 3.5.0
  MultiModeCode:
  - 2.0.0
  Prospino:
  - '2.1'
  Pythia:
  - '8.312'
  Rivet:
  - 4.1.0
  SPheno:
  - 3.3.8
  - 4.0.3
  SUSY_HIT:
  - '1.5'
  SuperIso:
  - '4.1'
  classy:
  - 2.6.3
  - 2.9.3
  - 2.9.4
  - 3.1.0
  classy_exo:
  - 2.7.2
  gamLike:
  - 1.0.0
  - 1.0.1
  gm2calc:
  - 1.2.0
  - 1.3.0
  nulike:
  - 1.0.4
  - 1.0.5
  - 1.0.6
  - 1.0.7
  - 1.0.8
  - 1.0.9
  obscura:
  - 1.1.0
  pbarlike:
  - '1.0'
  plc:
  - '3.0'
  salami:
  - 0.1.0
  simple_xs:
  - '1.0'
  vevacious:
  - '1.0'
  xsecBE:
  - 1.0.2
