#ifndef __boss__classes_ExampleBackend_1_234_hpp__
#define __boss__classes_ExampleBackend_1_234_hpp__

#ifndef __classes_hpp__
#define __classes_hpp__

#include <iostream>
#include <vector>
#include <ctime>
#include <map> 



#include "backend_types/ExampleBackend_1_234/abstract_ClassThree.hpp"
#include "gambit/Backends/abstracttypedefs.hpp"
#include "gambit/Backends/wrappertypedefs.hpp"
template <typename T>         
class ClassThree : public virtual Abstract_ClassThree<T> {
public:
  T pop();
  void push(T item);
  int size();

private:
  std::vector<T> stack;
  int curr_size;

  public:
    Abstract_ClassThree<T>* pointer_copy__BOSS();

    using Abstract_ClassThree<T>::pointer_assign__BOSS;
    void pointer_assign__BOSS(Abstract_ClassThree<T>* in);


};

// A dummy instantiation to ensure the <double> specialization is generated by the compiler
static ClassThree<double> __BOSS_dummy_ClassThree_double_instance__;



#endif
#endif /* __boss__classes_ExampleBackend_1_234_hpp__ */
