# \author Pengxuan Zhu
#         (pengxuan.zhu@adelaide.edu.au)
# \date 2026 Aug
#
# Shared compiler discovery and validation for CBS presets and toolchains.
# Keep this file compatible with the project's legacy CMake requirement; presets
# themselves require CMake 3.24 because their documented cache-reset command
# uses `cmake --fresh`.

include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/../compiler_mins.cmake")

set(CBS_PRESET_MIN_CMAKE_VERSION "3.24.0")
set(CBS_MIN_GNU_VERSION "${MIN_GCC_VERSION}")
set(CBS_MIN_INTEL_VERSION "${MIN_ICC_VERSION}")
set(CBS_MIN_CLANG_VERSION "${MIN_CLANG_VERSION}")
set(CBS_MIN_APPLECLANG_VERSION "${MIN_APPLECLANG_VERSION}")

# The ordered search policy is deliberately explicit.  New LLVM major versions
# should be added here when their behaviour has been reviewed for CBS/GAMBIT.
set(CBS_SUPPORTED_LLVM_MAJORS "22;21;20;19;18;17;16;15;14;13;12;11;10")

function(cbs_resolve_command output command)
  set(_cbs_command "${command}")
  if("${_cbs_command}" STREQUAL "")
    set(${output} "" PARENT_SCOPE)
    return()
  endif()

  separate_arguments(_cbs_command_parts NATIVE_COMMAND "${_cbs_command}")
  list(LENGTH _cbs_command_parts _cbs_command_length)
  if(_cbs_command_length EQUAL 0)
    set(${output} "" PARENT_SCOPE)
    return()
  endif()
  list(GET _cbs_command_parts 0 _cbs_executable)

  if(IS_ABSOLUTE "${_cbs_executable}")
    if(EXISTS "${_cbs_executable}")
      set(_cbs_resolved "${_cbs_executable}")
    else()
      set(_cbs_resolved "")
    endif()
  else()
    unset(_cbs_resolved CACHE)
    unset(_cbs_resolved)
    find_program(_cbs_resolved NAMES "${_cbs_executable}")
    if(NOT _cbs_resolved OR _cbs_resolved MATCHES "-NOTFOUND$")
      set(_cbs_resolved "")
    endif()
  endif()

  set(${output} "${_cbs_resolved}" PARENT_SCOPE)
endfunction()

function(cbs_classify_compiler compiler output_id output_version output_text)
  if("${compiler}" STREQUAL "" OR NOT EXISTS "${compiler}")
    set(${output_id} "" PARENT_SCOPE)
    set(${output_version} "" PARENT_SCOPE)
    set(${output_text} "Compiler executable was not found" PARENT_SCOPE)
    return()
  endif()

  execute_process(
    COMMAND "${compiler}" --version
    RESULT_VARIABLE _cbs_result
    OUTPUT_VARIABLE _cbs_stdout
    ERROR_VARIABLE _cbs_stderr
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_STRIP_TRAILING_WHITESPACE
    TIMEOUT 5)
  string(STRIP "${_cbs_stdout}\n${_cbs_stderr}" _cbs_text)
  string(REPLACE "\n" " " _cbs_text "${_cbs_text}")

  if(NOT _cbs_result EQUAL 0)
    set(${output_id} "" PARENT_SCOPE)
    set(${output_version} "" PARENT_SCOPE)
    set(${output_text} "${_cbs_text}" PARENT_SCOPE)
    return()
  endif()

  set(_cbs_id "")
  set(_cbs_version "")
  get_filename_component(_cbs_compiler_name "${compiler}" NAME)
  string(REGEX REPLACE "\\.[Ee][Xx][Ee]$" "" _cbs_compiler_name "${_cbs_compiler_name}")
  if(_cbs_text MATCHES "[Aa]pple[ \t]+[Cc]lang[ \t]+version[ \t]+([0-9]+(\\.[0-9]+)+)")
    set(_cbs_id "AppleClang")
    set(_cbs_version "${CMAKE_MATCH_1}")
  elseif(_cbs_text MATCHES "[Cc]lang[ \t]+version[ \t]+([0-9]+(\\.[0-9]+)+)")
    set(_cbs_id "Clang")
    set(_cbs_version "${CMAKE_MATCH_1}")
  elseif(_cbs_text MATCHES "Intel[^\n]*([0-9]+\\.[0-9]+(\\.[0-9]+)?)")
    set(_cbs_id "Intel")
    set(_cbs_version "${CMAKE_MATCH_1}")
  else()
    # GNU: gcc/g++ --version contains "gcc"/"g++".  Debian/Ubuntu /usr/bin/cc
    # prints "cc (Ubuntu ...)" and never mentions GNU, so also accept a
    # dumpversion plus Free Software Foundation / cc,c++,gcc,g++,gfortran.
    execute_process(
      COMMAND "${compiler}" -dumpfullversion -dumpversion
      RESULT_VARIABLE _cbs_gnu_version_result
      OUTPUT_VARIABLE _cbs_gnu_version_output
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET
      TIMEOUT 5)
    string(REGEX MATCH "[0-9]+\\.[0-9]+(\\.[0-9]+)?" _cbs_gnu_version
           "${_cbs_gnu_version_output}")
    if("${_cbs_gnu_version}" STREQUAL "")
      string(REGEX MATCH "[0-9]+\\.[0-9]+(\\.[0-9]+)?" _cbs_gnu_version
             "${_cbs_text}")
    endif()
    if(NOT "${_cbs_gnu_version}" STREQUAL "" AND (
        _cbs_text MATCHES "([Gg][Cc][Cc]|[Gg]\\+\\+|GNU|Free Software Foundation)" OR
        _cbs_compiler_name MATCHES "^(cc|c\\+\\+|gcc|g\\+\\+|gfortran)(-[0-9]+)?$"))
      set(_cbs_id "GNU")
      set(_cbs_version "${_cbs_gnu_version}")
    endif()
  endif()

  set(${output_id} "${_cbs_id}" PARENT_SCOPE)
  set(${output_version} "${_cbs_version}" PARENT_SCOPE)
  set(${output_text} "${_cbs_text}" PARENT_SCOPE)
endfunction()

function(cbs_compiler_is_supported compiler_id compiler_version output_supported output_reason)
  set(_cbs_supported FALSE)
  set(_cbs_reason "")

  if("${compiler_id}" STREQUAL "GNU")
    if("${compiler_version}" VERSION_LESS "${CBS_MIN_GNU_VERSION}")
      set(_cbs_reason "GNU ${compiler_version} is older than the required ${CBS_MIN_GNU_VERSION}")
    else()
      set(_cbs_supported TRUE)
    endif()
  elseif("${compiler_id}" STREQUAL "Clang")
    if("${compiler_version}" VERSION_LESS "${CBS_MIN_CLANG_VERSION}")
      set(_cbs_reason "Clang ${compiler_version} is older than the required ${CBS_MIN_CLANG_VERSION}")
    else()
      set(_cbs_supported TRUE)
    endif()
  elseif("${compiler_id}" STREQUAL "AppleClang")
    if("${compiler_version}" VERSION_LESS "${CBS_MIN_APPLECLANG_VERSION}")
      set(_cbs_reason "AppleClang ${compiler_version} is older than the required ${CBS_MIN_APPLECLANG_VERSION}")
    else()
      set(_cbs_supported TRUE)
    endif()
  elseif("${compiler_id}" STREQUAL "Intel")
    if("${compiler_version}" VERSION_LESS "${CBS_MIN_INTEL_VERSION}")
      set(_cbs_reason "Intel ${compiler_version} is older than the required ${CBS_MIN_INTEL_VERSION}")
    else()
      set(_cbs_supported TRUE)
    endif()
  elseif("${compiler_id}" STREQUAL "")
    set(_cbs_reason "Compiler identity or version could not be determined")
  else()
    set(_cbs_reason "Compiler family '${compiler_id}' is not in the GAMBIT support policy")
  endif()

  set(${output_supported} "${_cbs_supported}" PARENT_SCOPE)
  set(${output_reason} "${_cbs_reason}" PARENT_SCOPE)
endfunction()

function(cbs_validate_c_cxx_pair c_compiler cxx_compiler output_supported output_id output_version output_reason)
  cbs_classify_compiler("${c_compiler}" _cbs_c_id _cbs_c_version _cbs_c_text)
  cbs_classify_compiler("${cxx_compiler}" _cbs_cxx_id _cbs_cxx_version _cbs_cxx_text)

  if("${_cbs_c_id}" STREQUAL "")
    set(_cbs_supported FALSE)
    set(_cbs_reason "Could not identify the C compiler '${c_compiler}': ${_cbs_c_text}")
  elseif("${_cbs_cxx_id}" STREQUAL "")
    set(_cbs_supported FALSE)
    set(_cbs_reason "Could not identify the C++ compiler '${cxx_compiler}': ${_cbs_cxx_text}")
  elseif(NOT "${_cbs_c_id}" STREQUAL "${_cbs_cxx_id}")
    set(_cbs_supported FALSE)
    set(_cbs_reason "C compiler is ${_cbs_c_id}, but C++ compiler is ${_cbs_cxx_id}")
  elseif(NOT "${_cbs_c_version}" STREQUAL "${_cbs_cxx_version}")
    set(_cbs_supported FALSE)
    set(_cbs_reason "C compiler is ${_cbs_c_id} ${_cbs_c_version}, but C++ compiler is ${_cbs_cxx_id} ${_cbs_cxx_version}")
  else()
    cbs_compiler_is_supported("${_cbs_cxx_id}" "${_cbs_cxx_version}" _cbs_supported _cbs_reason)
  endif()

  set(${output_supported} "${_cbs_supported}" PARENT_SCOPE)
  set(${output_id} "${_cbs_cxx_id}" PARENT_SCOPE)
  set(${output_version} "${_cbs_cxx_version}" PARENT_SCOPE)
  set(${output_reason} "${_cbs_reason}" PARENT_SCOPE)
endfunction()

function(cbs_find_fortran_compiler output_path output_id output_version output_reason)
  set(_cbs_fortran "")
  if(DEFINED CMAKE_Fortran_COMPILER AND NOT "${CMAKE_Fortran_COMPILER}" STREQUAL "")
    cbs_resolve_command(_cbs_fortran "${CMAKE_Fortran_COMPILER}")
  elseif(NOT "$ENV{FC}" STREQUAL "")
    cbs_resolve_command(_cbs_fortran "$ENV{FC}")
  else()
    foreach(_cbs_candidate gfortran ifx ifort flang-new flang)
      cbs_resolve_command(_cbs_fortran "${_cbs_candidate}")
      if(_cbs_fortran)
        break()
      endif()
    endforeach()
  endif()

  if(_cbs_fortran)
    cbs_classify_compiler("${_cbs_fortran}" _cbs_id _cbs_version _cbs_text)
    set(_cbs_reason "")
  else()
    set(_cbs_id "")
    set(_cbs_version "")
    set(_cbs_reason "No Fortran compiler was found (tried FC, gfortran, ifx, ifort, flang-new, flang)")
  endif()

  set(${output_path} "${_cbs_fortran}" PARENT_SCOPE)
  set(${output_id} "${_cbs_id}" PARENT_SCOPE)
  set(${output_version} "${_cbs_version}" PARENT_SCOPE)
  set(${output_reason} "${_cbs_reason}" PARENT_SCOPE)
endfunction()

function(cbs_find_system_toolchain output_c output_cxx output_fortran output_id output_version output_reason)
  if(DEFINED CMAKE_C_COMPILER AND NOT "${CMAKE_C_COMPILER}" STREQUAL "")
    cbs_resolve_command(_cbs_c "${CMAKE_C_COMPILER}")
  elseif(NOT "$ENV{CC}" STREQUAL "")
    cbs_resolve_command(_cbs_c "$ENV{CC}")
  else()
    foreach(_cbs_candidate gcc clang cc)
      cbs_resolve_command(_cbs_c "${_cbs_candidate}")
      if(_cbs_c)
        break()
      endif()
    endforeach()
  endif()

  if(DEFINED CMAKE_CXX_COMPILER AND NOT "${CMAKE_CXX_COMPILER}" STREQUAL "")
    cbs_resolve_command(_cbs_cxx "${CMAKE_CXX_COMPILER}")
  elseif(NOT "$ENV{CXX}" STREQUAL "")
    cbs_resolve_command(_cbs_cxx "$ENV{CXX}")
  else()
    foreach(_cbs_candidate g++ clang++ c++)
      cbs_resolve_command(_cbs_cxx "${_cbs_candidate}")
      if(_cbs_cxx)
        break()
      endif()
    endforeach()
  endif()

  if(_cbs_c AND _cbs_cxx)
    cbs_validate_c_cxx_pair("${_cbs_c}" "${_cbs_cxx}" _cbs_supported _cbs_id _cbs_version _cbs_reason)
  elseif(NOT _cbs_c)
    set(_cbs_supported FALSE)
    set(_cbs_id "")
    set(_cbs_version "")
    set(_cbs_reason "No C compiler was found")
  else()
    set(_cbs_supported FALSE)
    set(_cbs_id "")
    set(_cbs_version "")
    set(_cbs_reason "No C++ compiler was found")
  endif()

  cbs_find_fortran_compiler(_cbs_fortran _cbs_fortran_id _cbs_fortran_version _cbs_fortran_reason)
  if(_cbs_supported AND NOT _cbs_fortran)
    set(_cbs_supported FALSE)
    set(_cbs_reason "${_cbs_fortran_reason}")
  endif()

  set(${output_c} "${_cbs_c}" PARENT_SCOPE)
  set(${output_cxx} "${_cbs_cxx}" PARENT_SCOPE)
  set(${output_fortran} "${_cbs_fortran}" PARENT_SCOPE)
  set(${output_id} "${_cbs_id}" PARENT_SCOPE)
  set(${output_version} "${_cbs_version}" PARENT_SCOPE)
  set(${output_reason} "${_cbs_reason}" PARENT_SCOPE)
endfunction()

function(cbs_try_llvm_directory bindir output_found output_c output_cxx output_version output_reason)
  set(_cbs_pairs "clang|clang++")
  foreach(_cbs_major ${CBS_SUPPORTED_LLVM_MAJORS})
    list(APPEND _cbs_pairs "clang-${_cbs_major}|clang++-${_cbs_major}")
  endforeach()

  foreach(_cbs_pair ${_cbs_pairs})
    string(REPLACE "|" ";" _cbs_pair_parts "${_cbs_pair}")
    list(GET _cbs_pair_parts 0 _cbs_c_name)
    list(GET _cbs_pair_parts 1 _cbs_cxx_name)
    set(_cbs_c "${bindir}/${_cbs_c_name}")
    set(_cbs_cxx "${bindir}/${_cbs_cxx_name}")
    if(NOT EXISTS "${_cbs_c}" OR NOT EXISTS "${_cbs_cxx}")
      continue()
    endif()

    cbs_classify_compiler("${_cbs_c}" _cbs_c_id _cbs_c_version _cbs_c_text)
    cbs_classify_compiler("${_cbs_cxx}" _cbs_cxx_id _cbs_cxx_version _cbs_cxx_text)
    if(NOT "${_cbs_c_id}" STREQUAL "Clang" OR NOT "${_cbs_cxx_id}" STREQUAL "Clang")
      continue()
    endif()
    if(NOT "${_cbs_c_version}" STREQUAL "${_cbs_cxx_version}")
      continue()
    endif()
    cbs_compiler_is_supported("Clang" "${_cbs_cxx_version}" _cbs_supported _cbs_reason)
    if(_cbs_supported)
      set(${output_found} TRUE PARENT_SCOPE)
      set(${output_c} "${_cbs_c}" PARENT_SCOPE)
      set(${output_cxx} "${_cbs_cxx}" PARENT_SCOPE)
      set(${output_version} "${_cbs_cxx_version}" PARENT_SCOPE)
      set(${output_reason} "" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${output_found} FALSE PARENT_SCOPE)
  set(${output_c} "" PARENT_SCOPE)
  set(${output_cxx} "" PARENT_SCOPE)
  set(${output_version} "" PARENT_SCOPE)
  set(${output_reason} "No supported upstream LLVM clang/clang++ pair was found in ${bindir}" PARENT_SCOPE)
endfunction()

function(cbs_find_llvm_toolchain output_found output_c output_cxx output_version output_origin output_reason)
  set(_cbs_dirs "")
  if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    cbs_resolve_command(_cbs_brew "brew")
    if(_cbs_brew)
      execute_process(
        COMMAND "${_cbs_brew}" --prefix llvm
        RESULT_VARIABLE _cbs_brew_result
        OUTPUT_VARIABLE _cbs_brew_prefix
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
      if(_cbs_brew_result EQUAL 0 AND EXISTS "${_cbs_brew_prefix}/bin")
        list(APPEND _cbs_dirs "${_cbs_brew_prefix}/bin")
      endif()
    endif()
    list(APPEND _cbs_dirs "/opt/homebrew/opt/llvm/bin" "/usr/local/opt/llvm/bin")
  endif()

  foreach(_cbs_major ${CBS_SUPPORTED_LLVM_MAJORS})
    list(APPEND _cbs_dirs
      "/usr/lib/llvm-${_cbs_major}/bin"
      "/usr/local/llvm-${_cbs_major}/bin"
      "/opt/llvm-${_cbs_major}/bin")
  endforeach()

  list(REMOVE_DUPLICATES _cbs_dirs)
  foreach(_cbs_dir ${_cbs_dirs})
    if(NOT EXISTS "${_cbs_dir}")
      continue()
    endif()
    cbs_try_llvm_directory("${_cbs_dir}" _cbs_found _cbs_c _cbs_cxx _cbs_version _cbs_reason)
    if(_cbs_found)
      set(${output_found} TRUE PARENT_SCOPE)
      set(${output_c} "${_cbs_c}" PARENT_SCOPE)
      set(${output_cxx} "${_cbs_cxx}" PARENT_SCOPE)
      set(${output_version} "${_cbs_version}" PARENT_SCOPE)
      set(${output_origin} "${_cbs_dir}" PARENT_SCOPE)
      set(${output_reason} "" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  foreach(_cbs_major ${CBS_SUPPORTED_LLVM_MAJORS})
    cbs_resolve_command(_cbs_versioned_c "clang-${_cbs_major}")
    cbs_resolve_command(_cbs_versioned_cxx "clang++-${_cbs_major}")
    if(_cbs_versioned_c AND _cbs_versioned_cxx)
      get_filename_component(_cbs_versioned_dir "${_cbs_versioned_cxx}" DIRECTORY)
      cbs_try_llvm_directory("${_cbs_versioned_dir}" _cbs_found _cbs_c _cbs_cxx _cbs_version _cbs_reason)
      if(_cbs_found)
        set(${output_found} TRUE PARENT_SCOPE)
        set(${output_c} "${_cbs_c}" PARENT_SCOPE)
        set(${output_cxx} "${_cbs_cxx}" PARENT_SCOPE)
        set(${output_version} "${_cbs_version}" PARENT_SCOPE)
        set(${output_origin} "${_cbs_versioned_dir}" PARENT_SCOPE)
        set(${output_reason} "" PARENT_SCOPE)
        return()
      endif()
    endif()
  endforeach()

  cbs_resolve_command(_cbs_path_c "clang")
  cbs_resolve_command(_cbs_path_cxx "clang++")
  if(_cbs_path_c AND _cbs_path_cxx)
    get_filename_component(_cbs_path_dir "${_cbs_path_cxx}" DIRECTORY)
    cbs_try_llvm_directory("${_cbs_path_dir}" _cbs_found _cbs_c _cbs_cxx _cbs_version _cbs_reason)
    if(_cbs_found)
      set(${output_found} TRUE PARENT_SCOPE)
      set(${output_c} "${_cbs_c}" PARENT_SCOPE)
      set(${output_cxx} "${_cbs_cxx}" PARENT_SCOPE)
      set(${output_version} "${_cbs_version}" PARENT_SCOPE)
      set(${output_origin} "${_cbs_path_dir}" PARENT_SCOPE)
      set(${output_reason} "" PARENT_SCOPE)
      return()
    endif()
  endif()

  set(${output_found} FALSE PARENT_SCOPE)
  set(${output_c} "" PARENT_SCOPE)
  set(${output_cxx} "" PARENT_SCOPE)
  set(${output_version} "" PARENT_SCOPE)
  set(${output_origin} "" PARENT_SCOPE)
  set(${output_reason} "No supported upstream LLVM clang/clang++ pair was found in the standard installation locations or PATH" PARENT_SCOPE)
endfunction()
