# \author Pengxuan Zhu
#         (pengxuan.zhu@adelaide.edu.au)
# \date 2026 Aug
#
# Read-only CBS preset availability probe.
# Usage:
#   cmake -P cmake/presets/detect-cbs-presets.cmake

cmake_minimum_required(VERSION 3.16)
include("${CMAKE_CURRENT_LIST_DIR}/CBSCompilerDiscovery.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/CBSPythonDiscovery.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/CBSRootDiscovery.cmake")

function(cbs_probe_print_compiler label compiler)
  if("${compiler}" STREQUAL "")
    return()
  endif()
  cbs_classify_compiler("${compiler}" _cbs_id _cbs_version _cbs_text)
  if(_cbs_id)
    message("  ${label} ${_cbs_id} ${_cbs_version} (${compiler})")
  else()
    message("  ${label} ${compiler}")
  endif()
endfunction()

function(cbs_probe_print_compilers c_compiler cxx_compiler)
  cbs_probe_print_compiler("C compiler   :" "${c_compiler}")
  cbs_probe_print_compiler("C++ compiler :" "${cxx_compiler}")
endfunction()

function(cbs_probe_print_fortran compiler)
  if("${compiler}" STREQUAL "")
    return()
  endif()
  cbs_classify_compiler("${compiler}" _cbs_id _cbs_version _cbs_text)
  if(_cbs_id)
    message("  Fortran      : ${_cbs_id} ${_cbs_version} (${compiler})")
  else()
    message("  Fortran      : ${compiler}")
  endif()
endfunction()

function(cbs_probe_print_python executable version)
  message("  Python       : ${version} (${executable})")
endfunction()

function(cbs_probe_first_existing output)
  foreach(_cbs_path ${ARGN})
    if(EXISTS "${_cbs_path}")
      set(${output} "${_cbs_path}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${output} "" PARENT_SCOPE)
endfunction()

function(cbs_probe_find_openmp output_found output_description output_reason)
  set(_cbs_openmp_found FALSE)
  set(_cbs_openmp_description "unavailable")
  set(_cbs_openmp_reason "")

  if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    cbs_resolve_command(_cbs_brew "brew")
    if(NOT _cbs_brew)
      set(_cbs_openmp_reason "Homebrew libomp was not found; run 'brew install libomp'")
    else()
      execute_process(
        COMMAND "${_cbs_brew}" --prefix libomp
        RESULT_VARIABLE _cbs_libomp_result
        OUTPUT_VARIABLE _cbs_libomp_prefix
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
      if(_cbs_libomp_result EQUAL 0 AND EXISTS "${_cbs_libomp_prefix}/lib/libomp.dylib")
        set(_cbs_openmp_found TRUE)
        set(_cbs_openmp_description "Homebrew libomp (${_cbs_libomp_prefix})")
      else()
        set(_cbs_openmp_reason "Homebrew libomp was not found; run 'brew install libomp'")
      endif()
    endif()
  else()
    cbs_resolve_command(_cbs_pkg_config "pkg-config")
    if(_cbs_pkg_config)
      execute_process(
        COMMAND "${_cbs_pkg_config}" --exists libgomp
        RESULT_VARIABLE _cbs_gomp_pc)
      if(NOT _cbs_gomp_pc EQUAL 0)
        execute_process(
          COMMAND "${_cbs_pkg_config}" --exists openmp
          RESULT_VARIABLE _cbs_gomp_pc)
      endif()
      if(_cbs_gomp_pc EQUAL 0)
        set(_cbs_openmp_found TRUE)
        set(_cbs_openmp_description "pkg-config OpenMP")
      endif()
    endif()
    if(NOT _cbs_openmp_found)
      file(GLOB _cbs_gomp_hits
        /usr/lib/libgomp.so*
        /usr/lib64/libgomp.so*
        /usr/lib/*/libgomp.so*
        /usr/lib/gcc/*/libgomp.so*
        /usr/lib/llvm-*/lib/libomp.so*
        /usr/lib64/libomp.so*
        /usr/lib/libomp.so*)
      if(_cbs_gomp_hits)
        list(GET _cbs_gomp_hits 0 _cbs_gomp_lib)
        set(_cbs_openmp_found TRUE)
        set(_cbs_openmp_description "${_cbs_gomp_lib}")
      else()
        set(_cbs_openmp_reason "libgomp/libomp was not found")
      endif()
    endif()
  endif()

  set(${output_found} "${_cbs_openmp_found}" PARENT_SCOPE)
  set(${output_description} "${_cbs_openmp_description}" PARENT_SCOPE)
  set(${output_reason} "${_cbs_openmp_reason}" PARENT_SCOPE)
endfunction()

function(cbs_probe_find_boost output_found output_path)
  set(_cbs_boost_hints "")
  if(DEFINED ENV{BOOST_INCLUDEDIR} AND NOT "$ENV{BOOST_INCLUDEDIR}" STREQUAL "")
    list(APPEND _cbs_boost_hints "$ENV{BOOST_INCLUDEDIR}/boost/version.hpp")
  endif()
  if(DEFINED ENV{BOOST_ROOT} AND NOT "$ENV{BOOST_ROOT}" STREQUAL "")
    list(APPEND _cbs_boost_hints "$ENV{BOOST_ROOT}/include/boost/version.hpp")
  endif()
  if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    cbs_resolve_command(_cbs_brew "brew")
    if(_cbs_brew)
      execute_process(
        COMMAND "${_cbs_brew}" --prefix boost
        RESULT_VARIABLE _cbs_brew_boost_result
        OUTPUT_VARIABLE _cbs_brew_boost_prefix
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
      if(_cbs_brew_boost_result EQUAL 0)
        list(APPEND _cbs_boost_hints "${_cbs_brew_boost_prefix}/include/boost/version.hpp")
      endif()
    endif()
  endif()
  list(APPEND _cbs_boost_hints
    /usr/include/boost/version.hpp
    /usr/local/include/boost/version.hpp
    /opt/local/include/boost/version.hpp)
  cbs_probe_first_existing(_cbs_boost ${_cbs_boost_hints})
  if(_cbs_boost)
    set(${output_found} TRUE PARENT_SCOPE)
    set(${output_path} "${_cbs_boost}" PARENT_SCOPE)
  else()
    set(${output_found} FALSE PARENT_SCOPE)
    set(${output_path} "" PARENT_SCOPE)
  endif()
endfunction()

function(cbs_probe_find_eigen output_found output_path)
  set(_cbs_eigen_hints "")
  if(DEFINED EIGEN3_INCLUDE_DIR AND NOT "${EIGEN3_INCLUDE_DIR}" STREQUAL "")
    list(APPEND _cbs_eigen_hints
      "${EIGEN3_INCLUDE_DIR}/Eigen/Core"
      "${EIGEN3_INCLUDE_DIR}/eigen3/Eigen/Core")
  endif()
  if(DEFINED ENV{EIGEN3_INCLUDE_DIR} AND NOT "$ENV{EIGEN3_INCLUDE_DIR}" STREQUAL "")
    list(APPEND _cbs_eigen_hints
      "$ENV{EIGEN3_INCLUDE_DIR}/Eigen/Core"
      "$ENV{EIGEN3_INCLUDE_DIR}/eigen3/Eigen/Core")
  endif()
  if(DEFINED ENV{EIGEN3_ROOT} AND NOT "$ENV{EIGEN3_ROOT}" STREQUAL "")
    list(APPEND _cbs_eigen_hints
      "$ENV{EIGEN3_ROOT}/include/eigen3/Eigen/Core"
      "$ENV{EIGEN3_ROOT}/Eigen/Core")
  endif()
  if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    cbs_resolve_command(_cbs_brew "brew")
    if(_cbs_brew)
      execute_process(
        COMMAND "${_cbs_brew}" --prefix eigen
        RESULT_VARIABLE _cbs_brew_eigen_result
        OUTPUT_VARIABLE _cbs_brew_eigen_prefix
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
      if(_cbs_brew_eigen_result EQUAL 0)
        list(APPEND _cbs_eigen_hints "${_cbs_brew_eigen_prefix}/include/eigen3/Eigen/Core")
      endif()
    endif()
  endif()
  list(APPEND _cbs_eigen_hints
    /usr/include/eigen3/Eigen/Core
    /usr/local/include/eigen3/Eigen/Core
    /opt/local/include/eigen3/Eigen/Core)
  cbs_probe_first_existing(_cbs_eigen ${_cbs_eigen_hints})
  if(_cbs_eigen)
    set(${output_found} TRUE PARENT_SCOPE)
    set(${output_path} "${_cbs_eigen}" PARENT_SCOPE)
  else()
    set(${output_found} FALSE PARENT_SCOPE)
    set(${output_path} "" PARENT_SCOPE)
  endif()
endfunction()

function(cbs_probe_find_gsl output_found output_path)
  cbs_resolve_command(_cbs_gsl_config "gsl-config")
  if(_cbs_gsl_config)
    set(${output_found} TRUE PARENT_SCOPE)
    set(${output_path} "${_cbs_gsl_config}" PARENT_SCOPE)
    return()
  endif()
  cbs_resolve_command(_cbs_pkg_config "pkg-config")
  if(_cbs_pkg_config)
    execute_process(
      COMMAND "${_cbs_pkg_config}" --exists gsl
      RESULT_VARIABLE _cbs_gsl_pc)
    if(_cbs_gsl_pc EQUAL 0)
      set(${output_found} TRUE PARENT_SCOPE)
      set(${output_path} "pkg-config gsl" PARENT_SCOPE)
      return()
    endif()
  endif()
  if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    cbs_resolve_command(_cbs_brew "brew")
    if(_cbs_brew)
      execute_process(
        COMMAND "${_cbs_brew}" --prefix gsl
        RESULT_VARIABLE _cbs_brew_gsl_result
        OUTPUT_VARIABLE _cbs_brew_gsl_prefix
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
      if(_cbs_brew_gsl_result EQUAL 0 AND EXISTS "${_cbs_brew_gsl_prefix}/bin/gsl-config")
        set(${output_found} TRUE PARENT_SCOPE)
        set(${output_path} "${_cbs_brew_gsl_prefix}/bin/gsl-config" PARENT_SCOPE)
        return()
      endif()
    endif()
  endif()
  set(${output_found} FALSE PARENT_SCOPE)
  set(${output_path} "" PARENT_SCOPE)
endfunction()

function(cbs_probe_print_optional_environment openmp_description root_found root_prefix root_version root_reason)
  message("  OpenMP       : ${openmp_description}")
  if(root_found)
    if(NOT "${root_version}" STREQUAL "")
      message("  ROOT         : ${root_version} (${root_prefix})")
    else()
      message("  ROOT         : detected (${root_prefix})")
    endif()
  elseif(NOT "${root_reason}" STREQUAL "")
    message("  ROOT         : skipped (${root_reason})")
  else()
    message("  ROOT         : unavailable (optional)")
  endif()
endfunction()

function(cbs_probe_print_core_deps boost_found eigen_found gsl_found)
  if(boost_found)
    message("  Boost        : found")
  else()
    message("  Boost        : missing (need Boost >= 1.48)")
  endif()
  if(eigen_found)
    message("  Eigen        : found")
  else()
    message("  Eigen        : missing (need Eigen >= 3.1)")
  endif()
  if(gsl_found)
    message("  GSL          : found")
  else()
    message("  GSL          : missing (need GSL >= 2.1)")
  endif()
endfunction()

function(cbs_probe_print_rivet_contur python_found python_executable sqlite_found)
  set(_cbs_backend_reasons "")
  if(NOT python_found)
    list(APPEND _cbs_backend_reasons "Python is unavailable")
  else()
    cbs_python_missing_modules("${python_executable}" _cbs_backend_missing Cython configobj pandas matplotlib)
    if(_cbs_backend_missing)
      string(REPLACE ";" ", " _cbs_backend_missing_text "${_cbs_backend_missing}")
      list(APPEND _cbs_backend_reasons "missing Python modules: ${_cbs_backend_missing_text}")
    endif()
  endif()
  if(NOT sqlite_found)
    list(APPEND _cbs_backend_reasons "SQLite3 development libraries were not found")
  endif()
  if(_cbs_backend_reasons)
    string(REPLACE ";" "; " _cbs_backend_reason_text "${_cbs_backend_reasons}")
    message("  Rivet/Contur : unavailable (${_cbs_backend_reason_text})")
  else()
    message("  Rivet/Contur : enabled by default (Rivet 4.1.0, Contur 3.0.0)")
  endif()
endfunction()

function(cbs_probe_find_sqlite3 output_found)
  # Keep this script read-only. `cmake --find-package` creates a CMakeFiles
  # directory in script mode, whereas pkg-config and Homebrew's prefix query do
  # not modify the source tree.
  cbs_resolve_command(_cbs_pkg_config "pkg-config")
  if(_cbs_pkg_config)
    execute_process(
      COMMAND "${_cbs_pkg_config}" --exists sqlite3
      RESULT_VARIABLE _cbs_sqlite_result
      ERROR_QUIET)
  else()
    set(_cbs_sqlite_result 1)
  endif()
  if(_cbs_sqlite_result EQUAL 0)
    set(${output_found} TRUE PARENT_SCOPE)
    return()
  endif()

  if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    cbs_resolve_command(_cbs_brew "brew")
    if(_cbs_brew)
      execute_process(
        COMMAND "${_cbs_brew}" --prefix sqlite
        RESULT_VARIABLE _cbs_brew_sqlite_result
        OUTPUT_VARIABLE _cbs_brew_sqlite_prefix
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
      if(_cbs_brew_sqlite_result EQUAL 0 AND
         EXISTS "${_cbs_brew_sqlite_prefix}/include/sqlite3.h" AND
         EXISTS "${_cbs_brew_sqlite_prefix}/lib/libsqlite3.dylib")
        set(${output_found} TRUE PARENT_SCOPE)
        return()
      endif()
    endif()
  endif()
  set(${output_found} FALSE PARENT_SCOPE)
endfunction()

message("")
message("CBS preset availability")
message("=======================")

if(CMAKE_VERSION VERSION_LESS CBS_PRESET_MIN_CMAKE_VERSION)
  set(_cbs_presets_supported FALSE)
  set(_cbs_presets_reason "CMake ${CMAKE_VERSION} is older than the ${CBS_PRESET_MIN_CMAKE_VERSION} required by CMakePresets.json")
else()
  set(_cbs_presets_supported TRUE)
  set(_cbs_presets_reason "")
endif()

cbs_find_system_toolchain(_cbs_system_c _cbs_system_cxx _cbs_system_fortran _cbs_system_id _cbs_system_version _cbs_system_reason)
set(_cbs_python_has_yaml FALSE)
cbs_discover_python(_cbs_python_found _cbs_python_executable _cbs_python_version _cbs_python_root _cbs_python_include _cbs_python_library _cbs_python_reason)
if(_cbs_python_found)
  cbs_python_has_module("${_cbs_python_executable}" yaml _cbs_python_has_yaml)
  if(NOT _cbs_python_has_yaml)
    set(_cbs_python_reason "Python ${_cbs_python_version} cannot import the required yaml module")
  endif()
endif()
cbs_probe_find_openmp(_cbs_openmp_found _cbs_openmp_description _cbs_openmp_reason)
cbs_find_root_installation(_cbs_root_found _cbs_root_prefix _cbs_root_version _cbs_root_reason)
cbs_probe_find_sqlite3(_cbs_sqlite_found)
cbs_probe_find_boost(_cbs_boost_found _cbs_boost_path)
cbs_probe_find_eigen(_cbs_eigen_found _cbs_eigen_path)
cbs_probe_find_gsl(_cbs_gsl_found _cbs_gsl_path)

set(_cbs_core_ok FALSE)
if(_cbs_presets_supported AND _cbs_python_found AND _cbs_python_has_yaml AND _cbs_openmp_found AND _cbs_boost_found AND _cbs_eigen_found AND _cbs_gsl_found)
  set(_cbs_core_ok TRUE)
endif()
set(_cbs_system_ok FALSE)
if(_cbs_core_ok AND _cbs_system_c AND _cbs_system_cxx AND _cbs_system_fortran AND NOT _cbs_system_reason)
  set(_cbs_system_ok TRUE)
endif()

if(_cbs_system_ok)
  message("")
  message("[AVAILABLE] cbs — System toolchain")
  cbs_probe_print_compilers("${_cbs_system_c}" "${_cbs_system_cxx}")
  cbs_probe_print_fortran("${_cbs_system_fortran}")
  cbs_probe_print_python("${_cbs_python_executable}" "${_cbs_python_version}")
  cbs_probe_print_core_deps("${_cbs_boost_found}" "${_cbs_eigen_found}" "${_cbs_gsl_found}")
  cbs_probe_print_optional_environment("${_cbs_openmp_description}" "${_cbs_root_found}" "${_cbs_root_prefix}" "${_cbs_root_version}" "${_cbs_root_reason}")
  cbs_probe_print_rivet_contur("${_cbs_python_has_yaml}" "${_cbs_python_executable}" "${_cbs_sqlite_found}")
else()
  message("")
  message("[UNAVAILABLE] cbs — System toolchain")
  if(NOT _cbs_presets_supported)
    message("  Reason         ${_cbs_presets_reason}")
  elseif(NOT _cbs_python_found OR NOT _cbs_python_has_yaml)
    message("  Reason         ${_cbs_python_reason}")
  elseif(NOT _cbs_openmp_found)
    message("  Reason         ${_cbs_openmp_reason}")
  elseif(NOT _cbs_boost_found)
    message("  Reason         Boost >= 1.48 was not found")
  elseif(NOT _cbs_eigen_found)
    message("  Reason         Eigen >= 3.1 was not found")
  elseif(NOT _cbs_gsl_found)
    message("  Reason         GSL >= 2.1 was not found")
  else()
    message("  Reason         ${_cbs_system_reason}")
  endif()
endif()

cbs_find_llvm_toolchain(_cbs_llvm_found _cbs_llvm_c _cbs_llvm_cxx _cbs_llvm_version _cbs_llvm_origin _cbs_llvm_reason)
cbs_find_fortran_compiler(_cbs_llvm_fortran _cbs_llvm_fortran_id _cbs_llvm_fortran_version _cbs_llvm_fortran_reason)
set(_cbs_llvm_ok FALSE)
if(_cbs_core_ok AND _cbs_llvm_found AND _cbs_llvm_fortran)
  set(_cbs_llvm_ok TRUE)
endif()
if(_cbs_llvm_ok)
  message("")
  message("[AVAILABLE] cbs-llvm — Upstream LLVM")
  cbs_probe_print_compilers("${_cbs_llvm_c}" "${_cbs_llvm_cxx}")
  cbs_probe_print_fortran("${_cbs_llvm_fortran}")
  cbs_probe_print_python("${_cbs_python_executable}" "${_cbs_python_version}")
  get_filename_component(_cbs_llvm_root "${_cbs_llvm_origin}" DIRECTORY)
  message("  LLVM root    : ${_cbs_llvm_root}")
  cbs_probe_print_core_deps("${_cbs_boost_found}" "${_cbs_eigen_found}" "${_cbs_gsl_found}")
  cbs_probe_print_optional_environment("${_cbs_openmp_description}" "${_cbs_root_found}" "${_cbs_root_prefix}" "${_cbs_root_version}" "${_cbs_root_reason}")
  cbs_probe_print_rivet_contur("${_cbs_python_has_yaml}" "${_cbs_python_executable}" "${_cbs_sqlite_found}")
else()
  message("")
  message("[UNAVAILABLE] cbs-llvm — Upstream LLVM")
  if(NOT _cbs_presets_supported)
    message("  Reason         ${_cbs_presets_reason}")
  elseif(NOT _cbs_python_found OR NOT _cbs_python_has_yaml)
    message("  Reason         ${_cbs_python_reason}")
  elseif(NOT _cbs_openmp_found)
    message("  Reason         ${_cbs_openmp_reason}")
  elseif(NOT _cbs_boost_found)
    message("  Reason         Boost >= 1.48 was not found")
  elseif(NOT _cbs_eigen_found)
    message("  Reason         Eigen >= 3.1 was not found")
  elseif(NOT _cbs_gsl_found)
    message("  Reason         GSL >= 2.1 was not found")
  elseif(NOT _cbs_llvm_found)
    message("  Reason         ${_cbs_llvm_reason}")
  else()
    message("  Reason         ${_cbs_llvm_fortran_reason}")
  endif()
endif()

if(_cbs_llvm_ok)
  message("")
  message("Next steps")
  message("----------")
  message("  cmake --preset cbs-llvm --fresh")
  message("  cmake --build --preset cbs-llvm")
elseif(_cbs_system_ok)
  message("")
  message("Next steps")
  message("----------")
  message("  cmake --preset cbs --fresh")
  message("  cmake --build --preset cbs")
endif()
