# \author Pengxuan Zhu
#         (pengxuan.zhu@adelaide.edu.au)
# \date 2026 Aug
#
# Final build summary for configurations selected through a CBS preset.

include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/presets/CBSCompilerDiscovery.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/CBSValidation.cmake")

function(cbs_print_compiler_summary)
  if(NOT CBS_PRESET_BUILD)
    return()
  endif()

  cbs_compiler_is_supported("${CMAKE_CXX_COMPILER_ID}" "${CMAKE_CXX_COMPILER_VERSION}" _cbs_supported _cbs_reason)

  set(_cbs_bits_text "ColliderBit (+ ScannerBit)")
  if(GAMBIT_BITS)
    set(_cbs_bits_text "${GAMBIT_BITS}")
    string(REPLACE ";" ", " _cbs_bits_text "${_cbs_bits_text}")
  endif()
  set(_cbs_interface_count "not trimmed")
  set(_cbs_kept "")
  if(GAMBIT_TRIM_BACKEND_INTERFACES AND GAMBIT_TRIM_TOTAL_COUNT)
    set(_cbs_kept "${GAMBIT_TRIM_USED_BACKENDS}")
    list(SORT _cbs_kept)
    set(_cbs_interface_count
        "${GAMBIT_TRIM_USED_COUNT} of ${GAMBIT_TRIM_TOTAL_COUNT} kept")
  endif()

  message(STATUS "")
  message(STATUS "================================================================")
  message(STATUS "                         CBS build summary")
  message(STATUS "----------------------------------------------------------------")
  cbs_summary_line("Preset" "${CBS_BUILD_PRESET}")
  if("${CBS_BUILD_PRESET}" STREQUAL "cbs-llvm")
    cbs_summary_line("Toolchain" "upstream LLVM ${CBS_RESOLVED_LLVM_VERSION}")
    cbs_summary_line("LLVM root" "${CBS_RESOLVED_LLVM_ROOT}")
  else()
    cbs_summary_line("Toolchain" "system environment")
  endif()
  cbs_summary_line("C" "${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION}  (${CMAKE_C_COMPILER})")
  cbs_summary_line("C++" "${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}  (${CMAKE_CXX_COMPILER})")
  cbs_summary_line("Fortran" "${CMAKE_Fortran_COMPILER_ID} ${CMAKE_Fortran_COMPILER_VERSION}  (${CMAKE_Fortran_COMPILER})")
  if(Python3_Interpreter_FOUND)
    cbs_summary_line("Python" "CPython ${Python3_VERSION}  (${Python3_EXECUTABLE})")
  endif()
  if(OPENMP_FOUND OR FOUND_BREW_OPENMP OR GAMBIT_MACOS_HOMEBREW_LLVM_OPENMP)
    cbs_summary_line("OpenMP" "enabled")
  else()
    cbs_summary_line("OpenMP" "unavailable")
  endif()
  cbs_summary_line("Bits" "${_cbs_bits_text}")
  cbs_summary_line("Interfaces" "${_cbs_interface_count}")
  foreach(_cbs_interface ${_cbs_kept})
    if(NOT "${_cbs_interface}" STREQUAL "")
      message(STATUS "    ${_cbs_interface}")
    endif()
  endforeach()
  message(STATUS "  ----------------------------------------------------------------")
  cbs_print_validation_summary()

  set(_cbs_hepmc "enabled")
  if(EXCLUDE_HEPMC)
    set(_cbs_hepmc "disabled")
  endif()
  if(CBS_HEPMC_VERSION)
    string(APPEND _cbs_hepmc " (${CBS_HEPMC_VERSION})")
  endif()
  set(_cbs_yoda "enabled")
  if(EXCLUDE_YODA)
    set(_cbs_yoda "disabled")
  endif()
  if(CBS_YODA_VERSION)
    string(APPEND _cbs_yoda " (${CBS_YODA_VERSION})")
  endif()
  set(_cbs_fastjet "enabled")
  if(EXCLUDE_FASTJET)
    set(_cbs_fastjet "disabled")
  endif()
  if(CBS_FASTJET_VERSION)
    string(APPEND _cbs_fastjet " (${CBS_FASTJET_VERSION})")
  endif()
  set(_cbs_fastjet_contrib "enabled")
  if(EXCLUDE_FJCONTRIB)
    set(_cbs_fastjet_contrib "disabled")
  endif()
  if(CBS_FJCONTRIB_VERSION)
    string(APPEND _cbs_fastjet_contrib " (${CBS_FJCONTRIB_VERSION})")
  endif()
  set(_cbs_python_bindings "enabled")
  if(NOT HAVE_PYBIND11)
    set(_cbs_python_bindings "disabled")
  endif()
  if(pybind11_VERSION)
    string(APPEND _cbs_python_bindings " (pybind11 ${pybind11_VERSION})")
  endif()
  set(_cbs_root "enabled")
  if(EXCLUDE_ROOT)
    if(CBS_ROOT_SKIP_REASON)
      set(_cbs_root "unavailable (${CBS_ROOT_SKIP_REASON})")
    elseif(CBS_AUTO_DETECT_ROOT)
      set(_cbs_root "unavailable")
    else()
      set(_cbs_root "disabled")
    endif()
  elseif(ROOT_VERSION)
    set(_cbs_root "enabled (ROOT ${ROOT_VERSION})")
  endif()
  set(_cbs_restframes "enabled")
  if(EXCLUDE_RESTFRAMES)
    if(WITH_RESTFRAMES AND EXCLUDE_ROOT)
      set(_cbs_restframes "unavailable (needs ROOT)")
    elseif(WITH_RESTFRAMES)
      set(_cbs_restframes "unavailable")
    else()
      set(_cbs_restframes "disabled")
    endif()
  endif()
  if(CBS_RESTFRAMES_VERSION)
    string(APPEND _cbs_restframes " (${CBS_RESTFRAMES_VERSION})")
  endif()
  set(_cbs_onnxruntime "enabled")
  if(EXCLUDE_ONNXRUNTIME)
    if(WITH_ONNXRUNTIME)
      set(_cbs_onnxruntime "unavailable")
    else()
      set(_cbs_onnxruntime "disabled")
    endif()
  endif()
  if(CBS_ONNXRUNTIME_VERSION AND NOT EXCLUDE_ONNXRUNTIME)
    string(APPEND _cbs_onnxruntime " (${CBS_ONNXRUNTIME_VERSION})")
  endif()
  set(_cbs_mpi "disabled")
  if(WITH_MPI)
    if(MPI_CXX_FOUND)
      set(_cbs_mpi "enabled")
      if(MPI_CXX_LIBRARY_VERSION_STRING)
        string(REPLACE "\r\n" "\n" _cbs_mpi_library_version "${MPI_CXX_LIBRARY_VERSION_STRING}")
        string(REPLACE "\n" ";" _cbs_mpi_library_version_lines "${_cbs_mpi_library_version}")
        list(GET _cbs_mpi_library_version_lines 0 _cbs_mpi_library_version)
        string(STRIP "${_cbs_mpi_library_version}" _cbs_mpi_library_version)
        string(APPEND _cbs_mpi " (${_cbs_mpi_library_version})")
      elseif(MPI_CXX_VERSION)
        string(APPEND _cbs_mpi " (MPI ${MPI_CXX_VERSION})")
      endif()
    else()
      set(_cbs_mpi "unavailable")
    endif()
  endif()
  set(_cbs_cutflow "disabled")
  if(CUTFLOW)
    set(_cbs_cutflow "enabled")
  endif()
  set(_cbs_lld "disabled")
  if(GAMBIT_USE_LLD_FOR_CBS)
    set(_cbs_lld "enabled")
  endif()
  set(_cbs_rivet "disabled")
  set(_cbs_contur "disabled")
  if(CBS_WITH_RIVET_CONTUR)
    if(CBS_RIVET_CONTUR_ENABLED)
      set(_cbs_rivet "enabled (Rivet ${Rivet_ver}; built with CBS)")
      set(_cbs_contur "enabled (Contur ${CBS_RESOLVED_CONTUR_VERSION}; built with CBS)")
    elseif(CBS_RIVET_CONTUR_PREREQUISITES_REASON)
      set(_cbs_rivet "unavailable (${CBS_RIVET_CONTUR_PREREQUISITES_REASON})")
      set(_cbs_contur "unavailable (${CBS_RIVET_CONTUR_PREREQUISITES_REASON})")
    else()
      set(_cbs_rivet "unavailable")
      set(_cbs_contur "unavailable")
    endif()
  endif()

  message(STATUS "  ----------------------------------------------------------------")
  message(STATUS "  CBS feature flags")
  cbs_summary_line("HepMC3" "${_cbs_hepmc}")
  cbs_summary_line("YODA" "${_cbs_yoda}")
  cbs_summary_line("FastJet" "${_cbs_fastjet}")
  cbs_summary_line("FastJet Contrib" "${_cbs_fastjet_contrib}")
  cbs_summary_line("Python bindings" "${_cbs_python_bindings}")
  cbs_summary_line("ROOT" "${_cbs_root}")
  cbs_summary_line("RestFrames" "${_cbs_restframes}")
  cbs_summary_line("ONNX Runtime" "${_cbs_onnxruntime}")
  cbs_summary_line("MPI" "${_cbs_mpi}")
  cbs_summary_line("Cutflow" "${_cbs_cutflow}")
  cbs_summary_line("lld linker" "${_cbs_lld}")
  message(STATUS "  ----------------------------------------------------------------")
  message(STATUS "  CBS optional backends")
  cbs_summary_line("Rivet" "${_cbs_rivet}")
  cbs_summary_line("Contur" "${_cbs_contur}")
  cbs_summary_line("Build tree" "${CMAKE_BINARY_DIR}")
  if(_cbs_supported)
    cbs_summary_line("Compatibility" "supported")
  else()
    cbs_summary_line("Compatibility" "unsupported (${_cbs_reason})")
  endif()
  message(STATUS "================================================================")
endfunction()
