//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  ColliderBit sources for model VLQ.
///
///  Automatically generated by GUM.
///
///  \author The GAMBIT Collaboration
///          http://gambit.hepforge.org
///  \date 11:38AM on June 05, 2024
///
///  *********************************************

#include "gambit/ColliderBit/getPy8Collider.hpp"
#include "gambit/ColliderBit/generateEventPy8Collider.hpp"


namespace Gambit
{
  namespace ColliderBit
  {

    // Get spectrum and decays for Pythia
    GET_SPECTRUM_AND_DECAYS_FOR_PYTHIA_NONSUSY(getSpectrumAndDecaysForPythia_VLQ, VLQ_spectrum)

    // Get Monte Carlo event generator
    GET_SPECIFIC_PYTHIA(getPythia_VLQ, Pythia_VLQ_default, _VLQ)
    GET_PYTHIA_AS_BASE_COLLIDER(getPythia_VLQAsBase)

    // Run event generator
    GET_PYTHIA_EVENT(generateEventPythia_VLQ, Pythia_VLQ_default::Pythia8::Event)

  }
}
