name: Test sync CI job

#on: workflow_dispatch

on:
  schedule:
    - cron:  '0 5 * * *'

permissions:
  contents: write

jobs:
  push_changes:
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        arch: [X64]
    defaults:
      run:
        shell: bash -eo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pull and push changes
      run: |
        git checkout origin/master
        echo "Pulling from Public Repo"
        git remote add public https://github.com/GambitBSM/gambit.git
        git pull public master

        echo "Pushing to Private Repo"
        git push origin master

